export const STAGE_SCOPE_SELECTION = "SCOPE_SELECTION";
export const STAGE_SCOPE1_SUB_SELECTION = "SCOPE1_SUB_SELECTION";
export const STAGE_FACTOR_CALCULATOR = "FACTOR_CALCULATOR";
export const STAGE_EMISSION_CALCULATOR = "EMISSION_CALCULATOR";
export const STAGE_SCOPE2 = "SCOPE2";
export const STAGE_SCOPE3 = "SCOPE3";
