/**
 * API Compendium Estimation of Greenhouse Gas Emissions
 * Standard Emission Factors
 * Ported from legacy emission-factors.js
 */

export interface ApiFactorUncertainty {
  co2?: number;
  ch4?: number;
  n2o?: number;
  [key: string]: any;
}

export interface ApiFactorItem {
  code?: string;
  hhv?: number;
  co2?: number;
  ch4?: number;
  n2o?: number;
  co?: number;
  uncertainty?: ApiFactorUncertainty;
  unit?: string;
  usage?: string[];
  baseUnit?: string;
  stream?: string;
  segment?: string;
  [key: string]: any;
}

export const API_FACTORS: Record<string, ApiFactorItem> = {
  // --- GASES ---
  "Natural Gas": {
    code: "NG",
    hhv: 1020, // Btu/scf
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    co: 0.04,
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "scf",
    // stream: "Upstream" - Removed to match all streams
  },
  "Natural Gas (Venting/Blowdown)": {
    code: "NG_Vent",
    co2: 0.010498,
    ch4: 0.63029,
    n2o: 0,
    co: 0,
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["venting"],
    stream: "Upstream",
    baseUnit: "scf",
  },
  "Coke Oven Gas": {
    code: "COG",
    hhv: 599,
    co2: 46.85,
    ch4: 0.00048,
    n2o: 0.0001,
    co: 0.03,
    uncertainty: { co2: 0.02, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    stream: "Downstream",
    baseUnit: "scf",
  },
  "Blast Furnace Gas": {
    code: "BFG",
    hhv: 92,
    co2: 274.32,
    ch4: 0.000022,
    n2o: 0.0001,
    co: 0.02,
    uncertainty: { co2: 0.02, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Downstream",
  },
  "Propane (Gas)": {
    code: "LPG_Gas",
    hhv: 2516,
    co2: 61.46,
    ch4: 0.003,
    n2o: 0.0006,
    co: 0.03,
    uncertainty: { co2: 0.01, ch4: 0.2, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Downstream",
    baseUnit: "scf",
  },
  // Table 3-8: 1,470 Btu/scf, 92.3 wt % C; Table 4-6
  Acetylene: {
    code: "Acetylene",
    hhv: 1470,
    co2: 71.59,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  // API Compendium Tables 4-5 / 4-6 (HHV), per gallon of liquid
  Propylene: {
    code: "Propylene",
    hhv: 91000,
    co2: 67.77,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "gal",
  },
  // API Compendium Tables 4-5 / 4-6 (HHV), per gallon of liquid
  Butane: {
    code: "Butane",
    hhv: 103000,
    co2: 64.77,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "gal",
  },
  // API Compendium Tables 4-5 / 4-6 (HHV), per gallon of liquid
  Isobutane: {
    code: "Isobutane",
    hhv: 99000,
    co2: 64.94,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "gal",
  },
  // API Compendium Tables 4-5 / 4-6 (HHV), naphtha < 401 F
  Naphtha: {
    code: "Naphtha",
    hhv: 125000,
    co2: 68.02,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "gal",
  },
  "Compressed Natural Gas (CNG)": {
    code: "CNG",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Liquefied Natural Gas (LNG)": {
    code: "LNG",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },

  // --- FLARING-SPECIFIC GASES ---
  "Natural Gas (Flaring - Elevated)": {
    code: "NG_Flare_Elev",
    co2: 1.9039,
    ch4: 0.012447,
    n2o: 3.173e-06,
    co: 0.0035,
    combustionEfficiency: 0.965,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring - Enclosed)": {
    code: "NG_Flare_Enc",
    co2: 1.9039,
    ch4: 0.012447,
    n2o: 3.173e-06,
    co: 0.003,
    combustionEfficiency: 0.965,
    uncertainty: { co2: 0.02, ch4: 0.2, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring)": {
    code: "NG_Flare",
    co2: 1.9039,
    ch4: 0.012447,
    n2o: 3.173e-06,
    co: 0.0035,
    combustionEfficiency: 0.965,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Associated Gas (Flaring)": {
    code: "AG_Flare",
    co2: 2.2414,
    ch4: 0.010836,
    n2o: 3.736e-06,
    co: 0.004,
    uncertainty: { co2: 0.03, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  // Equation 5-3 carbon balance at 96.5 % combustion (Dec 2025 corrections) (379.3 scf/lbmol); N2O Equation 5-6
  "Propane (Flaring)": {
    code: "LPG_Flare",
    co2: 5.3793,
    ch4: 0.0,
    n2o: 8.9655e-06,
    unit: "kg/m³",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0, n2o: 0.5 },
    baseUnit: "m3",
  },
  // Equation 5-3 carbon balance at 96.5 % combustion (Dec 2025 corrections) (379.3 scf/lbmol); N2O Equation 5-6
  "Butane (Flaring)": {
    code: "Butane_Flare",
    co2: 7.1724,
    ch4: 0.0,
    n2o: 1.1954e-05,
    unit: "kg/m³",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0, n2o: 0.5 },
    baseUnit: "m3",
  },
  // Equation 5-3 carbon balance at 96.5 % combustion (Dec 2025 corrections) (379.3 scf/lbmol); N2O Equation 5-6
  "Ethylene (Flaring)": {
    code: "Ethylene_Flare",
    co2: 3.5862,
    ch4: 0.0,
    n2o: 5.977e-06,
    unit: "kg/m³",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0, n2o: 0.5 },
    baseUnit: "m3",
  },
  // Equation 5-3 carbon balance at 96.5 % combustion (Dec 2025 corrections) (379.3 scf/lbmol); N2O Equation 5-6
  "Propylene (Flaring)": {
    code: "Propylene_Flare",
    co2: 5.3793,
    ch4: 0.0,
    n2o: 8.9655e-06,
    unit: "kg/m³",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0, n2o: 0.5 },
    baseUnit: "m3",
  },

  // --- COMBUSTION - EQUIPMENT SPECIFIC (API Compendium Sec 4) ---
  // Table 4-7 (t/10^12 J HHV) in kg/MMBtu
  "Natural Gas - 4-Stroke Lean Burn Engine": {
    code: "NG_4SLB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.56656,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.3 },
    baseUnit: "scf",
  },
  // Table 4-7 (t/10^12 J HHV) in kg/MMBtu
  "Natural Gas - 4-Stroke Rich Burn Engine": {
    code: "NG_4SRB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.10551,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.3 },
    baseUnit: "scf",
  },
  // Table 4-7 (t/10^12 J HHV) in kg/MMBtu
  "Natural Gas - 2-Stroke Lean Burn Engine": {
    code: "NG_2SLB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.6573,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.2 },
    baseUnit: "scf",
  },
  // Table 4-7 (t/10^12 J HHV) in kg/MMBtu
  "Natural Gas - Turbine": {
    code: "NG_Turbine",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.003904,
    n2o: 0.001372,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - Heater/Boiler": {
    code: "NG_Heater",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },

  // --- LIQUIDS ---
  "Diesel (No. 2 Fuel Oil)": {
    code: "DSL",
    hhv: 138000,
    co2: 73.96,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream" - Removed to make available to Upstream Drilling
    baseUnit: "gal",
  },
  "Residual Fuel Oil (No. 6)": {
    code: "RFO",
    hhv: 150000,
    co2: 75.1,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  Kerosene: {
    code: "Kero",
    hhv: 135000,
    co2: 75.2,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Motor Gasoline": {
    code: "GAS",
    hhv: 125000,
    co2: 70.22,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Jet Fuel": {
    code: "JET",
    hhv: 135000,
    co2: 72.22,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Propane (Liquid)": {
    code: "LPG_Liq",
    hhv: 91000,
    co2: 62.87,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  Ethane: {
    code: "Ethane",
    hhv: 68000,
    co2: 59.6,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "gal",
  },
  "Ethane (Gas)": {
    code: "EthaneGas",
    hhv: 1768.8, // Btu/scf, API Compendium 2021 Table 3-7
    co2: 59.6,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "scf",
  },
  "Crude Oil": {
    code: "Crude",
    hhv: 138000,
    co2: 74.54,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },
  Lubricants: {
    code: "Lube",
    hhv: 144000,
    co2: 74.27,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },
  "Waste Oil": {
    code: "WasteOil",
    hhv: 138000,
    co2: 74.0,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },

  // --- SOLIDS ---
  "Anthracite Coal": {
    code: "CoalAnth",
    hhv: 25090,
    co2: 103.69,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Bituminous Coal": {
    code: "CoalBit",
    hhv: 24930,
    co2: 93.28,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Sub-Bituminous Coal": {
    code: "CoalSub",
    hhv: 17250,
    co2: 97.17,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Lignite Coal": {
    code: "CoalLig",
    hhv: 14210,
    co2: 97.72,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Petroleum Coke": {
    code: "PetCoke",
    hhv: 30000,
    co2: 102.41,
    ch4: 0.032,
    n2o: 0.0042,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  // Table 4-5; 40 CFR 98 Table C-2, kBtu per short ton
  Tires: {
    code: "Tires",
    hhv: 28000,
    co2: 85.97,
    ch4: 0.032,
    n2o: 0.0042,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    baseUnit: "ton",
  },

  // --- EQUIPMENT / SOURCE SPECIFIC (Added from Legacy) ---
  // Onshore equipment-leak factors are served by the server catalog (the fugitives form uses it).

  // --- WELL COMPLETIONS (API Compendium 2021 Tables 6-5 and 6-6) ---
  "Gas Well Completion - Hydraulic Fracturing (Uncontrolled / Vented)": {
    code: "CompGasHF_Uncontrolled",
    co2: 0,
    ch4: 28.8,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Gas Well Completion with Hydraulic Fracturing - Venting (Uncontrolled)",
    source: "5",
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Gas Well Completion - Hydraulic Fracturing (REC with Venting)": {
    code: "CompGasHF_REC",
    co2: 0,
    ch4: 13.542,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Gas Well Completion with Hydraulic Fracturing - REC with Venting",
    source: "5",
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Oil Well Completion - Hydraulic Fracturing (Uncontrolled / Vented)": {
    code: "CompOilHF_Uncontrolled",
    co2: 0,
    ch4: 14.419,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Oil Well Completion with Hydraulic Fracturing - Venting (Uncontrolled)",
    source: "5",
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Oil Well Completion - Hydraulic Fracturing (REC with Venting)": {
    code: "CompOilHF_REC",
    co2: 0,
    ch4: 0.615,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Oil Well Completion with Hydraulic Fracturing - REC with Venting",
    source: "5",
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Gas Well Completion - Without Hydraulic Fracturing (Vented)": {
    code: "CompGasNoHF_Vented",
    co2: 0,
    ch4: 1.7376,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Gas Well Completion without Hydraulic Fracturing - Vented (117.3 mscf/event)",
    source: "6",
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Oil Well Completion - Without Hydraulic Fracturing (Vented)": {
    code: "CompOilNoHF_Vented",
    co2: 0,
    ch4: 0.0141,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Oil Well Completion without Hydraulic Fracturing - Vented (0.95 mscf/event)",
    source: "6",
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  // Legacy Completion Defaults (Backwards Compatibility)
  "Completion - Gas Well (No Flaring)": {
    code: "CompGasNoFlare",
    ch4: 1.7376,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["completions"],
    description: "Average per event (Uncontrolled)",
    uncertainty: { ch4: 0.3 },
  },
  "Workover - Gas Well (No Flaring)": {
    code: "WorkoverGasNoFlare",
    ch4: 0.047,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["completions"],
    description: "Average per event (Uncontrolled)",
    uncertainty: { ch4: 0.3 },
  },
  "Liquids Unloading - Plunger Lift": {
    code: "UnloadPlunger",
    ch4: 1.774,
    co2: 0,
    n2o: 0,
    whole_gas_ef: 113466.0,
    ch4_mol_pct: 81.6,
    unit: "tonnes CH4/well-year",
    baseUnit: "wells",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Liquid Unloading Vented Emission Factor, plunger lift (1,774 kg CH4/well-year)",
    uncertainty: { co2: 0.50, ch4: 0.50, n2o: 0.50 },
  },
  "Liquids Unloading - Non-Plunger": {
    code: "UnloadNonPlunger",
    ch4: 2.792,
    co2: 0,
    n2o: 0,
    whole_gas_ef: 178531.0,
    ch4_mol_pct: 81.6,
    unit: "tonnes CH4/well-year",
    baseUnit: "wells",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Liquid Unloading Vented Emission Factor, non-plunger (2,792 kg CH4/well-year)",
    uncertainty: { co2: 0.50, ch4: 0.50, n2o: 0.50 },
  },
  "Liquids Unloading - Plunger (≤100 events/yr)": {
    code: "UnloadPlungerLE100",
    ch4: 0.185,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Plunger Lift ≤100 events/yr (0.185 tonnes CH4/event)",
    uncertainty: { ch4: 0.285 },
  },
  "Liquids Unloading - Plunger (>100 events/yr)": {
    code: "UnloadPlungerGT100",
    ch4: 0.024,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Plunger Lift >100 events/yr (0.024 tonnes CH4/event)",
    uncertainty: { ch4: 0.667 },
  },
  "Liquids Unloading - Non-Plunger (≤10 events/yr)": {
    code: "UnloadNonPlungerLE10",
    ch4: 0.412,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Non-Plunger ≤10 events/yr (0.412 tonnes CH4/event)",
    uncertainty: { ch4: 0.758 },
  },
  "Liquids Unloading - Non-Plunger (10-50 events/yr)": {
    code: "UnloadNonPlunger10To50",
    ch4: 0.462,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Non-Plunger 10-50 events/yr (0.462 tonnes CH4/event)",
    uncertainty: { ch4: 1.09 },
  },
  "Liquids Unloading - Non-Plunger (>50 events/yr)": {
    code: "UnloadNonPlungerGT50",
    ch4: 0.670,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Non-Plunger >50 events/yr (0.670 tonnes CH4/event)",
    uncertainty: { ch4: 0.514 },
  },
  "Drilling - Gas Well Drilling (Simplified Default)": {
    code: "DrillWellDefault",
    ch4: 0.0524,
    co2: 0,
    n2o: 0,
    uncertainty: { ch4: 0.25 },
    unit: "t CH4/well",
    baseUnit: "well",
    usage: ["drilling"],
    description: "Gas Well Drilling Simplified Default",
  },
  // Table 6-2 onshore, tonnes CH4 per drilling day
  "Drilling - Mud Degassing (Water Based)": {
    code: "MudWater",
    mud_type: "water_based",
    ch4: 0.0458,
    co2: 0,
    n2o: 0,
    unit: "t CH4/day",
    baseUnit: "days",
    usage: ["drilling"],
    uncertainty: { co2: 0.1, ch4: 0.5, n2o: 0.1 },
    description: "Water-based mud degassing (onshore)",
  },
  // Table 6-2 onshore, tonnes CH4 per drilling day
  "Drilling - Mud Degassing (Oil Based)": {
    code: "MudOil",
    mud_type: "oil_based",
    ch4: 0.0103,
    co2: 0,
    n2o: 0,
    unit: "t CH4/day",
    baseUnit: "days",
    usage: ["drilling"],
    uncertainty: { co2: 0.1, ch4: 0.5, n2o: 0.1 },
    description: "Oil-based mud degassing (onshore)",
  },
  // Table 6-2 onshore, tonnes CH4 per drilling day
  "Drilling - Mud Degassing (Synthetic)": {
    code: "MudSynthetic",
    mud_type: "synthetic",
    ch4: 0.0103,
    co2: 0,
    n2o: 0,
    unit: "t CH4/day",
    baseUnit: "days",
    usage: ["drilling"],
    uncertainty: { co2: 0.1, ch4: 0.5, n2o: 0.1 },
    description: "Synthetic mud degassing (onshore)",
  },

  "Dehydrator - Glycol (Uncontrolled)": {
    code: "DehyUncont",
    // API Compendium 5.3: ~0.82 kg CH4 per MMscf throughput → 0.00082 tonnes/MMscf
    ch4: 0.0052859,
    co2: 0,
    n2o: 0,
    unit: "tonnes CH4/MMscf",
    baseUnit: "MMscf",
    usage: ["dehydrator"],
    description: "Glycol Dehydrator Venting (Uncontrolled)",
    uncertainty: { ch4: 0.5 },
  },
  // --- ACID GAS REMOVAL (AGR) ---

  // --- LOADING LOSSES (API Section 5.2) ---

  // --- WASTEWATER / SEPARATION ---

  // --- BLOWDOWN / VENTING DETAILED ---

  // --- DEHYDRATORS (API Section 5.3) ---

  // --- PNEUMATIC DEVICES (API Section 5.2) ---

  // --- STORAGE TANKS (API Section 4.4) ---
  "Tank - Flash Emissions (Oil)": {
    code: "TankFlashOil",
    ch4: 0.193,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["tank_flashing"],
    description: "Default crude oil flash emission factor",
    uncertainty: { ch4: 0.4, co2: 0.15 },
  },

  // --- CHEMICAL PRODUCTION (API Section 6, Table 6-167) ---
  "Acrylonitrile": {
    code: "ACN_Prod",
    co2: 1.00,
    ch4: 0.00018,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Acrylonitrile process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Carbon Black": {
    code: "CB_Prod",
    co2: 2.63,
    ch4: 0.0287,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Carbon Black process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Ethylene Dichloride": {
    code: "EDC_Prod",
    co2: 0.041,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "EDC process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Ethylene Oxide": {
    code: "ETO_Prod",
    co2: 0.46,
    ch4: 0.00179,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Ethylene Oxide process CO₂",
    uncertainty: { co2: 0.10 },
  },
  "Methanol": {
    code: "MEOH_Prod",
    co2: 0.67,
    ch4: 0.0023,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Methanol process CO₂ + CH₄",
    uncertainty: { co2: 0.10, ch4: 0.20 },
  },

  // --- NITRIC ACID N₂O (API Section 6, pg 407) ---
  "Nitric Acid - With NSCR": {
    code: "HNO3_NSCR",
    co2: 0,
    ch4: 0,
    n2o: 2.0,
    unit: "kg N₂O/tonne product",
    usage: ["nitric_acid_production"],
    description: "Nitric acid with NSCR abatement",
    uncertainty: { n2o: 0.10 },
  },
  "Nitric Acid - Without NSCR": {
    code: "HNO3_NoNSCR",
    co2: 0,
    ch4: 0,
    n2o: 9.0,
    unit: "kg N₂O/tonne product",
    usage: ["nitric_acid_production"],
    description: "Nitric acid without NSCR abatement",
    uncertainty: { n2o: 0.20 },
  },

  // --- ADIPIC ACID N₂O (API Section 6, pg 407) ---
  "Adipic Acid - Thermal Abatement": {
    code: "AA_Thermal",
    co2: 0,
    ch4: 0,
    n2o: 13.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "Adipic acid with thermal abatement",
    uncertainty: { n2o: 0.10 },
  },
  "Adipic Acid - Catalytic Abatement": {
    code: "AA_Catalytic",
    co2: 0,
    ch4: 0,
    n2o: 53.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "Adipic acid with catalytic abatement",
    uncertainty: { n2o: 0.15 },
  },
  "Adipic Acid - Uncontrolled": {
    code: "AA_Uncontrolled",
    co2: 0,
    ch4: 0,
    n2o: 300.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "Adipic acid uncontrolled",
    uncertainty: { n2o: 0.30 },
  },

  // --- ASPHALT BLOWING (API Section 6, Table 6-52) ---
  "Asphalt": {
    code: "ASPH_Blow",
    co2: 5.61, // Table 6-52: 5.61E-03 t CO2/ton
    ch4: 3.07, // Table 6-52: 3.07E-03 t CH4/ton
    n2o: 0,
    unit: "kg/ton",
    usage: ["asphalt_blowing"],
    description: "Asphalt blowing process emissions",
    uncertainty: { co2: 0.30, ch4: 0.30 },
  },
  // --- ASSOCIATED GAS VENTING (API Section 6.3.1, Table 6-8) ---
  "Associated Gas Venting - US Average": {
    code: "AGV_US_AVG",
    co2: 0,
    ch4: 1.4,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 89.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting"],
    description: "Associated gas venting US average",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Gulf Coast Basin (Basin 220)": {
    code: "AGV_GULF_COAST",
    co2: 0,
    ch4: 0.7,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 47.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting"],
    description: "Gulf Coast Basin 220",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Anadarko Basin (Basin 360)": {
    code: "AGV_ANADARKO",
    co2: 0,
    ch4: 9.7,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 622.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting"],
    description: "Anadarko Basin 360",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Williston Basin (Basin 395)": {
    code: "AGV_WILLISTON",
    co2: 0,
    ch4: 8.9,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 570.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting"],
    description: "Williston Basin 395",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Permian Basin (Basin 430)": {
    code: "AGV_PERMIAN",
    co2: 0,
    ch4: 6.5,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 419.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting"],
    description: "Permian Basin 430",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Other US Basins": {
    code: "AGV_OTHER",
    co2: 0,
    ch4: 0.4,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 26.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting"],
    description: "Other US Basins",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
};
export const PROCESS_TYPES: Record<string, string> = {
  combustion: "Stationary Combustion",
  flaring: "Flaring",
  routine_flaring: "Routine Flaring",
  non_routine_flaring: "Non-Routine Flaring",
  safety_flaring: "Safety Flaring",
  associated_gas_venting: "Associated Gas Venting",
  venting: "Venting (Blowdown)",
  pneumatic: "Pneumatic Device",
  tank_flashing: "Storage Tank - Flashing/Events",
  tank_working: "Storage Tank - Working Losses",
  tank_breathing: "Storage Tank - Breathing Losses",
  drilling: "Drilling Operations",
  completions: "Well Completions & Workovers",
  unloading: "Liquids Unloading",
  agr: "Acid Gas Removal (AGR)",
  dehydrator: "Dehydrator",
  mobile: "Mobile Combustion",
  fugitive: "Onshore Equipment Leaks / Fugitives",
  loading: "Loading Losses",
  separation: "Wastewater / Separation",
  chemical_production: "Chemical Production (Process CO₂)",
  nitric_acid_production: "Nitric Acid Production (Process N₂O)",
  adipic_acid_production: "Adipic Acid Production (Process N₂O)",
  asphalt_blowing: "Asphalt Blowing",
  indirect_steam: "Indirect Steam / Heat (Section 8)",
  cogen_allocation: "Cogeneration Allocation (Section 8)",
  well_testing: "Well Testing",
  workovers: "Workovers (no hydraulic fracturing)",
  casing_gas: "Casing Gas Venting",
  compressor_venting: "Compressor Venting (seals / rod packing)",
  non_routine_venting: "Non-Routine Venting (blowdowns, PRVs, dig-ins)",
  vented_gas: "Vented / Flared Gas Volume",
  desiccant_dehydrator: "Desiccant Dehydrator",
  co2_eor: "CO₂ EOR Venting",
  thermal_oxidizer: "Thermal Oxidizer",
};

export interface ProcessGroupItem {
  id: string;
  label: string;
  options: string[];
}

export const PROCESS_GROUPS: ProcessGroupItem[] = [
  {
    id: "Upstream",
    label: "Upstream (Exploration & Production)",
    options: [
      "associated_gas_venting",
      "drilling",
      "well_testing",
      "completions",
      "workovers",
      "unloading",
      "casing_gas",
      "vented_gas",
      // production-segment glycol dehydrators and AGR (Tables 6-17, 6-18, 6-19)
      "dehydrator",
      "agr",
      "desiccant_dehydrator",
      "co2_eor",
      "compressor_venting",
      "non_routine_venting",
      "combustion",
      "flaring",
      "routine_flaring",
      "non_routine_flaring",
      "safety_flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
      "separation",
    ],
  },
  {
    id: "Midstream",
    label: "Midstream (Processing & Transmission)",
    options: [
      "agr",
      "dehydrator",
      "desiccant_dehydrator",
      "compressor_venting",
      "non_routine_venting",
      "thermal_oxidizer",
      "combustion",
      "flaring",
      "routine_flaring",
      "non_routine_flaring",
      "safety_flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
    ],
  },
  {
    id: "Downstream",
    label: "Downstream (Refining & Distribution)",
    options: [
      "combustion",
      "flaring",
      "routine_flaring",
      "non_routine_flaring",
      "safety_flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
      "thermal_oxidizer",
      "non_routine_venting",
      "separation",
      "chemical_production",
      "nitric_acid_production",
      "adipic_acid_production",
      "asphalt_blowing",
    ],
  },
];
