/**
 * API Compendium Estimation of Greenhouse Gas Emissions
 * Standard Emission Factors
 * Ported from legacy emission-factors.js
 */

export const API_FACTORS = {
  // --- GASES ---
  "Natural Gas": {
    code: "NG",
    hhv: 1020, // Btu/scf
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    co: 0.04,
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "scf",
    // stream: "Upstream" - Removed to match all streams
  },
  "Natural Gas (Venting/Blowdown)": {
    code: "NG_Vent",
    co2: 0.054,
    ch4: 0.67,
    n2o: 0,
    co: 0,
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["venting"],
    stream: "Upstream",
    baseUnit: "scf",
  },
  "Landfill Gas": {
    code: "LFG",
    hhv: 500,
    co2: 52.07,
    ch4: 0.0032,
    n2o: 0.00063,
    co: 0.05,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "scf",
  },
  "Coke Oven Gas": {
    code: "COG",
    hhv: 590,
    co2: 46.85,
    ch4: 0.00048,
    n2o: 0.0001,
    co: 0.03,
    uncertainty: { co2: 0.02, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    stream: "Downstream",
    baseUnit: "scf",
  },
  "Blast Furnace Gas": {
    code: "BFG",
    hhv: 92,
    co2: 274.32,
    ch4: 0.000022,
    n2o: 0.0001,
    co: 0.02,
    uncertainty: { co2: 0.02, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Downstream",
  },
  "Propane (Gas)": {
    code: "LPG_Gas",
    hhv: 2500,
    co2: 61.46,
    ch4: 0.003,
    n2o: 0.0006,
    co: 0.03,
    uncertainty: { co2: 0.01, ch4: 0.2, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Downstream",
    baseUnit: "scf",
  },
  Acetylene: {
    code: "Acetylene",
    hhv: 1477, // Btu/scf
    co2: 73.0, // approx
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Propylene: {
    code: "Propylene",
    hhv: 2332,
    co2: 68.0,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Butane: {
    code: "Butane",
    hhv: 3280,
    co2: 65.0,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Isobutane: {
    code: "Isobutane",
    hhv: 3253,
    co2: 64.9,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Naphtha: {
    code: "Naphtha",
    hhv: 5.24e6, // btu/bbl? need standardizing. Using per MMBtu factors usually.
    // API Compendium Table 3-8 default CO2 factors.
    co2: 68.02,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "bbl",
  },
  "Compressed Natural Gas (CNG)": {
    code: "CNG",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Liquefied Natural Gas (LNG)": {
    code: "LNG",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },

  // --- FLARING-SPECIFIC GASES ---
  "Natural Gas (Flaring - Elevated)": {
    code: "NG_Flare_Elev",
    co2: 1.92,
    ch4: 0.012,
    n2o: 0.00001,
    co: 0.0035,
    combustionEfficiency: 0.98,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring - Ground)": {
    code: "NG_Flare_Ground",
    co2: 1.88,
    ch4: 0.024,
    n2o: 0.00001,
    co: 0.004,
    combustionEfficiency: 0.96,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "",
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring - Enclosed)": {
    code: "NG_Flare_Enc",
    co2: 1.94,
    ch4: 0.006,
    n2o: 0.00001,
    co: 0.003,
    combustionEfficiency: 0.99,
    uncertainty: { co2: 0.02, ch4: 0.2, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring)": {
    code: "NG_Flare",
    co2: 1.92,
    ch4: 0.012,
    n2o: 0.00001,
    co: 0.0035,
    combustionEfficiency: 0.98,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Associated Gas (Flaring)": {
    code: "AG_Flare",
    co2: 2.15,
    ch4: 0.018,
    n2o: 0.00001,
    co: 0.004,
    uncertainty: { co2: 0.03, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Sour Gas (Flaring)": {
    code: "SG_Flare",
    co2: 2.3,
    ch4: 0.015,
    n2o: 0.00001,
    co: 0.0038,
    uncertainty: { co2: 0.03, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Propane (Flaring)": {
    code: "LPG_Flare",
    co2: 63.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu", // Usually volume or energy? API varies. Sticking to energy/mass foundation.
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },
  "Butane (Flaring)": {
    code: "Butane_Flare",
    co2: 65.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },
  "Ethylene (Flaring)": {
    code: "Ethylene_Flare",
    co2: 69.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },
  "Propylene (Flaring)": {
    code: "Propylene_Flare",
    co2: 68.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },

  // --- COMBUSTION - EQUIPMENT SPECIFIC (API Compendium Sec 4) ---
  "Natural Gas - 4-Stroke Lean Burn Engine": {
    code: "NG_4SLB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.3, // Example high methane slip: kg/MMBtu
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    description: "High CH4 Slip",
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.3 },
    baseUnit: "scf",
  },
  "Natural Gas - 4-Stroke Rich Burn Engine": {
    code: "NG_4SRB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001, // Controlled
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - 2-Stroke Lean Burn Engine": {
    code: "NG_2SLB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.6, // Very high slip
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - Turbine": {
    code: "NG_Turbine",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.0037,
    n2o: 0.0013,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - Heater/Boiler": {
    code: "NG_Heater",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },

  // --- LIQUIDS ---
  "Diesel (No. 2 Fuel Oil)": {
    code: "DSL",
    hhv: 138000,
    co2: 73.96,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream" - Removed to make available to Upstream Drilling
    baseUnit: "gal",
  },
  "Residual Fuel Oil (No. 6)": {
    code: "RFO",
    hhv: 150000,
    co2: 75.1,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  Kerosene: {
    code: "Kero",
    hhv: 135000,
    co2: 75.2,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Motor Gasoline": {
    code: "GAS",
    hhv: 125000,
    co2: 70.22,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Jet Fuel": {
    code: "JET",
    hhv: 135000,
    co2: 72.22,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Propane (Liquid)": {
    code: "LPG_Liq",
    hhv: 91500,
    co2: 62.88,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  Ethane: {
    code: "Ethane",
    hhv: 69600,
    co2: 59.6,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "gal",
  },
  "Ethane (Gas)": {
    code: "EthaneGas",
    hhv: 1768.8, // Btu/scf, API Compendium 2021 Table 3-7
    co2: 59.6,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "scf",
  },
  "Ethanol (100%)": {
    code: "EtOH",
    hhv: 84000,
    co2: 68.44,
    ch4: 0.0011,
    n2o: 0.0001,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    baseUnit: "gal",
  },
  "Biodiesel (100%)": {
    code: "BioDSL",
    hhv: 128000,
    co2: 73.84,
    ch4: 0.001,
    n2o: 0.0001,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    baseUnit: "gal",
  },
  "Crude Oil": {
    code: "Crude",
    hhv: 138000,
    co2: 74.54,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },
  Lubricants: {
    code: "Lube",
    hhv: 144000,
    co2: 74.27,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },
  "Waste Oil": {
    code: "WasteOil",
    hhv: 138000,
    co2: 74.0,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },

  // --- SOLIDS ---
  "Anthracite Coal": {
    code: "CoalAnth",
    hhv: 25090,
    co2: 103.69,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Bituminous Coal": {
    code: "CoalBit",
    hhv: 24930,
    co2: 93.26,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Sub-Bituminous Coal": {
    code: "CoalSub",
    hhv: 17250,
    co2: 97.17,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Lignite Coal": {
    code: "CoalLig",
    hhv: 14210,
    co2: 97.72,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Petroleum Coke": {
    code: "PetCoke",
    hhv: 30000,
    co2: 102.41,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Wood / Wood Waste": {
    code: "Wood",
    hhv: 8000,
    co2: 93.8,
    ch4: 0.0072,
    n2o: 0.0036,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  Tires: {
    code: "Tires",
    hhv: 28000,
    co2: 85.97,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
  },
  "Glycol Dehydrator": {
    code: "DEHY",
    co2: 0,
    ch4: 0,
    n2o: 0,
    unit: "hours",
    usage: ["dehydrator"],
    stream: "Midstream",
    uncertainty: { ch4: 0.5 },
  },
  "Desiccant Dehydrator": {
    code: "DehyDesiccant",
    ch4: 0,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["dehydrator"],
    description: "Desiccant Dehydrator (Batch)",
    uncertainty: { ch4: 0.5 },
  },

  // --- EQUIPMENT / SOURCE SPECIFIC (Added from Legacy) ---
  "Pneumatic Controller - High Bleed": {
    code: "HighBleed",
    ch4: 8.304,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Continuous bleed (gas processing)",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Controller - Low Bleed": {
    code: "LowBleed",
    ch4: 0.0939,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Pneumatic/hydraulic valve operator",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Controller - Intermittent": {
    code: "Intermittent",
    ch4: 0.4,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Intermittent vent controller",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Controller - Continuous Vent (T&S)": {
    code: "ContinuousVentTS",
    ch4: 3.5,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Continuous vent controller",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Pump - Chemical Injection (Piston)": {
    code: "PumpPiston",
    ch4: 2.65, // API 2021 Table 6-25
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Pump - Chemical Injection (Diaphragm)": {
    code: "PumpDiaphragm",
    ch4: 2.82, // API 2021 Table 6-25
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    uncertainty: { ch4: 0.3 },
  },
  // Onshore equipment-leak factors are served by the server catalog (the fugitives form uses it).

  "Methane Flashing - Crude Oil (Small Tank)": {
    code: "TankCrudeSmall",
    ch4: 0.18,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "<= 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Crude Oil (Large Tank)": {
    code: "TankCrudeLarge",
    ch4: 0.12,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "> 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Production Condensate (Small Tank)": {
    code: "TankProdSmall",
    ch4: 1.56,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "<= 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Production Condensate (Large Tank)": {
    code: "TankProdLarge",
    ch4: 1.16,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "> 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Produced Water (Tank)": {
    code: "TankWater",
    ch4: 0.01,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "Atmospheric Tank - Produced Water",
    uncertainty: { ch4: 0.4 },
  },
  // --- WELL COMPLETIONS (API Compendium 2021 Tables 6-5 and 6-6) ---
  "Gas Well Completion - Hydraulic Fracturing (Uncontrolled / Vented)": {
    code: "CompGasHF_Uncontrolled",
    co2: 0.252,
    ch4: 28.8,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Gas Well Completion with Hydraulic Fracturing - Venting (Uncontrolled)",
    source: "5",
    whole_gas_mscf: 1944.0,
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Gas Well Completion - Hydraulic Fracturing (REC with Venting)": {
    code: "CompGasHF_REC",
    co2: 0.118,
    ch4: 13.542,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Gas Well Completion with Hydraulic Fracturing - REC with Venting",
    source: "5",
    whole_gas_mscf: 914.0,
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Oil Well Completion - Hydraulic Fracturing (Uncontrolled / Vented)": {
    code: "CompOilHF_Uncontrolled",
    co2: 0.134,
    ch4: 14.419,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Oil Well Completion with Hydraulic Fracturing - Venting (Uncontrolled)",
    source: "5",
    whole_gas_mscf: 973.0,
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Oil Well Completion - Hydraulic Fracturing (REC with Venting)": {
    code: "CompOilHF_REC",
    co2: 0.005,
    ch4: 0.615,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Oil Well Completion with Hydraulic Fracturing - REC with Venting",
    source: "5",
    whole_gas_mscf: 41.5,
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Gas Well Completion - Without Hydraulic Fracturing (Vented)": {
    code: "CompGasNoHF_Vented",
    co2: 0.0152,
    ch4: 1.7376,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Gas Well Completion without Hydraulic Fracturing - Vented (117.3 mscf/event)",
    source: "6",
    whole_gas_mscf: 117.3,
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  "Oil Well Completion - Without Hydraulic Fracturing (Vented)": {
    code: "CompOilNoHF_Vented",
    co2: 0.00013,
    ch4: 0.0141,
    n2o: 0.0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["completions", "vented"],
    description: "Oil Well Completion without Hydraulic Fracturing - Vented (0.95 mscf/event)",
    source: "6",
    whole_gas_mscf: 0.95,
    ch4_mol_pct: 78.8,
    co2_mol_pct: 0.44,
    uncertainty: { co2: 0.40, ch4: 0.40, n2o: 0.0 },
  },
  // Legacy Completion Defaults (Backwards Compatibility)
  "Completion - Gas Well (No Flaring)": {
    code: "CompGasNoFlare",
    ch4: 0.7,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["completions"],
    description: "Average per event (Uncontrolled)",
    uncertainty: { ch4: 0.3 },
  },
  "Workover - Gas Well (No Flaring)": {
    code: "WorkoverGasNoFlare",
    ch4: 0.05,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["completions"],
    description: "Average per event (Uncontrolled)",
    uncertainty: { ch4: 0.3 },
  },
  "Liquids Unloading - Plunger Lift": {
    code: "UnloadPlunger",
    ch4: 1.774,
    co2: 0,
    n2o: 0,
    whole_gas_ef: 113466.0,
    ch4_mol_pct: 81.6,
    unit: "tonnes CH4/well-year",
    baseUnit: "wells",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Liquid Unloading Vented Emission Factor, plunger lift (1,774 kg CH4/well-year)",
    uncertainty: { co2: 0.50, ch4: 0.50, n2o: 0.50 },
  },
  "Liquids Unloading - Non-Plunger": {
    code: "UnloadNonPlunger",
    ch4: 2.792,
    co2: 0,
    n2o: 0,
    whole_gas_ef: 178531.0,
    ch4_mol_pct: 81.6,
    unit: "tonnes CH4/well-year",
    baseUnit: "wells",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Liquid Unloading Vented Emission Factor, non-plunger (2,792 kg CH4/well-year)",
    uncertainty: { co2: 0.50, ch4: 0.50, n2o: 0.50 },
  },
  "Liquids Unloading - Plunger (≤100 events/yr)": {
    code: "UnloadPlungerLE100",
    ch4: 0.185,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Plunger Lift ≤100 events/yr (0.185 tonnes CH4/event)",
    uncertainty: { ch4: 0.285 },
  },
  "Liquids Unloading - Plunger (>100 events/yr)": {
    code: "UnloadPlungerGT100",
    ch4: 0.024,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Plunger Lift >100 events/yr (0.024 tonnes CH4/event)",
    uncertainty: { ch4: 0.667 },
  },
  "Liquids Unloading - Non-Plunger (≤10 events/yr)": {
    code: "UnloadNonPlungerLE10",
    ch4: 0.412,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Non-Plunger ≤10 events/yr (0.412 tonnes CH4/event)",
    uncertainty: { ch4: 0.758 },
  },
  "Liquids Unloading - Non-Plunger (10-50 events/yr)": {
    code: "UnloadNonPlunger10To50",
    ch4: 0.462,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Non-Plunger 10-50 events/yr (0.462 tonnes CH4/event)",
    uncertainty: { ch4: 1.09 },
  },
  "Liquids Unloading - Non-Plunger (>50 events/yr)": {
    code: "UnloadNonPlungerGT50",
    ch4: 0.670,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    baseUnit: "events",
    usage: ["unloading", "liquids_unloading", "vented"],
    description: "Non-Plunger >50 events/yr (0.670 tonnes CH4/event)",
    uncertainty: { ch4: 0.514 },
  },
  "Drilling - Gas Well Drilling (Simplified Default)": {
    code: "DrillWellDefault",
    ch4: 0.0524,
    co2: 0,
    n2o: 0,
    uncertainty: { ch4: 0.25 },
    unit: "t CH4/well",
    baseUnit: "well",
    usage: ["drilling"],
    description: "Gas Well Drilling Simplified Default",
  },
  "Drilling - Mud Degassing (Water Based)": {
    code: "MudWater",
    ch4: 0.0458,
    co2: 0,
    n2o: 0,
    uncertainty: { ch4: 0.15 },
    unit: "t CH4/day",
    baseUnit: "days",
    usage: ["drilling"],
    description: "Water Based Mud Degassing (Onshore)",
  },
  "Drilling - Mud Degassing (Oil Based)": {
    code: "MudOil",
    ch4: 0.0103,
    co2: 0,
    n2o: 0,
    uncertainty: { ch4: 0.15 },
    unit: "t CH4/day",
    baseUnit: "days",
    usage: ["drilling"],
    description: "Oil Based Mud Degassing (Onshore)",
  },

  "Dehydrator - Glycol (Uncontrolled)": {
    code: "DehyUncont",
    // API Compendium 5.3: ~0.82 kg CH4 per MMscf throughput → 0.00082 tonnes/MMscf
    ch4: 0.00082,
    co2: 0,
    n2o: 0,
    unit: "tonnes/MMscf",
    baseUnit: "MMscf",
    usage: ["dehydrator"],
    description: "Glycol Dehydrator Venting (Uncontrolled)",
    uncertainty: { ch4: 0.5 },
  },
  "Dehydrator - Glycol (Controlled)": {
    code: "DehyCont",
    // Controlled: ~90% reduction from uncontrolled
    ch4: 0.000082,
    co2: 0,
    n2o: 0,
    unit: "tonnes/MMscf",
    baseUnit: "MMscf",
    usage: ["dehydrator"],
    description: "Glycol Dehydrator Venting (w/ Emission Control)",
    uncertainty: { ch4: 0.5 },
  },
  // --- ACID GAS REMOVAL (AGR) ---
  "Amine Unit - Venting (Generic)": {
    code: "AmineVent",
    ch4: 0.026, // Placeholder based on API/GRI generic if specific data missing
    co2: 1.1, // Varies heavily by gas composition (tonnes/MMscf throughput?)
    n2o: 0,
    unit: "tonnes/MMscf",
    usage: ["agr"],
    description: "Amine Unit Venting (Default)",
    uncertainty: { co2: 0.3, ch4: 0.5 },
  },

  // --- LOADING LOSSES (API Section 5.2) ---
  "Loading - Crude Oil (Tank Truck)": {
    code: "LoadCrudeTruck",
    ch4: 0.00016, // Factor from API: ~1.6 lb/1000 gal -> converted to kg/bbl or similar?
    // API Table 5-12: Submerged loading: 2.1 lb/1000 gal VOC. CH4 fraction small.
    // Using simplified default for now: kg/bbl
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    description: "Truck Loading (Submerged)",
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Crude Oil (Rail)": {
    code: "LoadCrudeRail",
    ch4: 0.00016,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Crude Oil (Marine Vessel)": {
    code: "LoadCrudeMarine",
    ch4: 0.00008, // API Marine typically lower loss rates
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Condensate (Tank Truck)": {
    code: "LoadCondTruck",
    ch4: 0.0005, // Higher volatility
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Gasoline (Tank Truck)": {
    code: "LoadGasTruck",
    ch4: 0.0, // Mostly VOCs, practically zero CH4?
    // API says Gasoline vapor is VOC. But for completeness we track.
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },

  // --- WASTEWATER / SEPARATION ---
  "Separator Venting - Gas Well": {
    code: "SepVentGas",
    ch4: 0.058,
    co2: 0.003,
    n2o: 0,
    unit: "kg/m3",
    baseUnit: "m3",
    usage: ["separation"],
    description: "Separator vent losses (gas well service)",
    uncertainty: { co2: 0.3, ch4: 0.4 },
  },
  "Separator Venting - Oil Well": {
    code: "SepVentOil",
    ch4: 0.012,
    co2: 0.001,
    n2o: 0,
    unit: "kg/m3",
    baseUnit: "m3",
    usage: ["separation"],
    description: "Separator vent losses (oil well service)",
    uncertainty: { co2: 0.3, ch4: 0.4 },
  },
  "Wastewater - CH4 (Open System)": {
    code: "WastewaterCH4",
    ch4: 0.0006,
    co2: 0,
    n2o: 0,
    unit: "kg/m3",
    baseUnit: "m3",
    usage: ["separation"],
    description: "Produced water / wastewater open system",
    uncertainty: { ch4: 0.5 },
  },
  "Wastewater - Oil/Water Separator": {
    code: "WaterSep",
    ch4: 0.0005,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl water",
    baseUnit: "bbl",
    usage: ["separation"],
    description: "Separator",
    uncertainty: { ch4: 0.5 },
  },

  // --- BLOWDOWN / VENTING DETAILED ---
  "Blowdown - Compressor (Reciprocating)": {
    code: "BlowdownCompRecip",
    ch4: 0.15, // tonnes/event default? or m3?
    co2: 0.01,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["venting"],
    uncertainty: { ch4: 0.4, co2: 0.2 },
  },
  "Blowdown - Compressor (Centrifugal)": {
    code: "BlowdownCompCent",
    ch4: 0.25,
    co2: 0.01,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["venting"],
    uncertainty: { ch4: 0.4, co2: 0.2 },
  },
  "Blowdown - Pipeline": {
    code: "BlowdownPipe",
    ch4: 1.5,
    co2: 0.05,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["venting"],
    description: "Generic Pipeline Blowdown",
    uncertainty: { ch4: 0.4, co2: 0.2 },
  },

  // --- DEHYDRATORS (API Section 5.3) ---
  "Dehydrator - TEG (No Controls)": {
    code: "DehydTEGNoCtrl",
    ch4: 3.0,
    co2: 0,
    n2o: 0,
    unit: "scf/gal TEG",
    usage: ["dehydrator"],
    description: "TEG Dehydrator without emission controls",
    uncertainty: { ch4: 0.5 },
  },
  "Dehydrator - TEG (Flash Tank)": {
    code: "DehydTEGFlash",
    ch4: 1.2,
    co2: 0,
    n2o: 0,
    unit: "scf/gal TEG",
    usage: ["dehydrator"],
    description: "TEG Dehydrator with flash tank separator",
    uncertainty: { ch4: 0.5 },
  },
  "Dehydrator - TEG (Condenser)": {
    code: "DehydTEGCond",
    ch4: 0.3,
    co2: 0,
    n2o: 0,
    unit: "scf/gal TEG",
    usage: ["dehydrator"],
    description: "TEG Dehydrator with condenser",
    uncertainty: { ch4: 0.5 },
  },

  // --- PNEUMATIC DEVICES (API Section 5.2) ---
  "Pneumatic Device - High Bleed": {
    code: "PneumHighBleed",
    ch4: 37.3,
    co2: 0,
    n2o: 0,
    unit: "scf/hr/device",
    usage: ["pneumatic"],
    description: "High-bleed pneumatic device",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Device - Low Bleed": {
    code: "PneumLowBleed",
    ch4: 1.39,
    co2: 0,
    n2o: 0,
    unit: "scf/hr/device",
    usage: ["pneumatic"],
    description: "Low-bleed pneumatic device",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Device - Intermittent": {
    code: "PneumIntermit",
    ch4: 13.5,
    co2: 0,
    n2o: 0,
    unit: "scf/event",
    usage: ["pneumatic"],
    description: "Intermittent bleed pneumatic device",
    uncertainty: { ch4: 0.3 },
  },

  // --- STORAGE TANKS (API Section 4.4) ---
  "Tank - Flash Emissions (Oil)": {
    code: "TankFlashOil",
    ch4: 0.193,
    co2: 0.012,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["tank_flashing"],
    description: "Default crude oil flash emission factor",
    uncertainty: { ch4: 0.4, co2: 0.15 },
  },
  "Tank - Working Losses (Oil)": {
    code: "TankWorkOil",
    ch4: 0.05,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["tank_working"],
    description: "Working losses",
    uncertainty: { ch4: 0.4 },
  },
  "Tank - Breathing Losses (Oil)": {
    code: "TankBreathOil",
    ch4: 0.001,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl-year",
    usage: ["tank_breathing"],
    description: "Standing storage breathing losses",
    uncertainty: { ch4: 0.4 },
  },

  // --- CHEMICAL PRODUCTION (API Section 6, Table 6-167) ---
  "Acrylonitrile": {
    code: "ACN_Prod",
    co2: 1.00,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Acrylonitrile process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Carbon Black": {
    code: "CB_Prod",
    co2: 2.63,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Carbon Black process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Ethylene": {
    code: "ETH_Prod",
    co2: 0.77,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Ethylene process CO₂",
    uncertainty: { co2: 0.10 },
  },
  "Ethylene Dichloride": {
    code: "EDC_Prod",
    co2: 0.041,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "EDC process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Ethylene Oxide": {
    code: "ETO_Prod",
    co2: 0.46,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Ethylene Oxide process CO₂",
    uncertainty: { co2: 0.10 },
  },
  "Methanol": {
    code: "MEOH_Prod",
    co2: 0.67,
    ch4: 0.0023,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "Methanol process CO₂ + CH₄",
    uncertainty: { co2: 0.10, ch4: 0.20 },
  },

  // --- NITRIC ACID N₂O (API Section 6, pg 407) ---
  "Nitric Acid - With NSCR": {
    code: "HNO3_NSCR",
    co2: 0,
    ch4: 0,
    n2o: 2.0,
    unit: "kg N₂O/tonne product",
    usage: ["nitric_acid_production"],
    description: "Nitric acid with NSCR abatement",
    uncertainty: { n2o: 0.10 },
  },
  "Nitric Acid - Without NSCR": {
    code: "HNO3_NoNSCR",
    co2: 0,
    ch4: 0,
    n2o: 9.0,
    unit: "kg N₂O/tonne product",
    usage: ["nitric_acid_production"],
    description: "Nitric acid without NSCR abatement",
    uncertainty: { n2o: 0.20 },
  },

  // --- ADIPIC ACID N₂O (API Section 6, pg 407) ---
  "Adipic Acid - Thermal Abatement": {
    code: "AA_Thermal",
    co2: 0,
    ch4: 0,
    n2o: 13.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "Adipic acid with thermal abatement",
    uncertainty: { n2o: 0.10 },
  },
  "Adipic Acid - Catalytic Abatement": {
    code: "AA_Catalytic",
    co2: 0,
    ch4: 0,
    n2o: 53.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "Adipic acid with catalytic abatement",
    uncertainty: { n2o: 0.15 },
  },
  "Adipic Acid - Uncontrolled": {
    code: "AA_Uncontrolled",
    co2: 0,
    ch4: 0,
    n2o: 300.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "Adipic acid uncontrolled",
    uncertainty: { n2o: 0.30 },
  },

  // --- ASPHALT BLOWING (API Section 6, Table 6-52) ---
  "Asphalt": {
    code: "ASPH_Blow",
    co2: 5.61, // Table 6-52: 5.61E-03 t CO2/ton
    ch4: 3.07, // Table 6-52: 3.07E-03 t CH4/ton
    n2o: 0,
    unit: "kg/ton",
    usage: ["asphalt_blowing"],
    description: "Asphalt blowing process emissions",
    uncertainty: { co2: 0.30, ch4: 0.30 },
  },
  // --- ASSOCIATED GAS VENTING (API Section 6.3.1, Table 6-8) ---
  "Associated Gas Venting - US Average": {
    code: "AGV_US_AVG",
    co2: 0,
    ch4: 1.4,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 89.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting", "venting"],
    description: "Associated gas venting US average",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Gulf Coast Basin (Basin 220)": {
    code: "AGV_GULF_COAST",
    co2: 0,
    ch4: 0.7,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 47.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting", "venting"],
    description: "Gulf Coast Basin 220",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Anadarko Basin (Basin 360)": {
    code: "AGV_ANADARKO",
    co2: 0,
    ch4: 9.7,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 622.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting", "venting"],
    description: "Anadarko Basin 360",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Williston Basin (Basin 395)": {
    code: "AGV_WILLISTON",
    co2: 0,
    ch4: 8.9,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 570.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting", "venting"],
    description: "Williston Basin 395",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Permian Basin (Basin 430)": {
    code: "AGV_PERMIAN",
    co2: 0,
    ch4: 6.5,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 419.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting", "venting"],
    description: "Permian Basin 430",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
  "Associated Gas Venting - Other US Basins": {
    code: "AGV_OTHER",
    co2: 0,
    ch4: 0.4,
    n2o: 0,
    unit: "kg CH4/bbl",
    whole_gas_ef: 26.0,
    ch4_mol_basis: 0.816,
    usage: ["associated_gas_venting", "venting"],
    description: "Other US Basins",
    uncertainty: { co2: 0.20, ch4: 0.40 },
    baseUnit: "bbl",
  },
};
export const PROCESS_TYPES = {
  combustion: "Stationary Combustion",
  flaring: "Flaring",
  routine_flaring: "Routine Flaring",
  non_routine_flaring: "Non-Routine Flaring",
  safety_flaring: "Safety Flaring",
  associated_gas_venting: "Associated Gas Venting",
  venting: "Venting (Blowdown)",
  pneumatic: "Pneumatic Device",
  tank_flashing: "Storage Tank - Flashing/Events",
  tank_working: "Storage Tank - Working Losses",
  tank_breathing: "Storage Tank - Breathing Losses",
  drilling: "Drilling Operations",
  completions: "Well Completions & Workovers",
  unloading: "Liquids Unloading",
  agr: "Acid Gas Removal (AGR)",
  dehydrator: "Dehydrator",
  mobile: "Mobile Combustion",
  fugitive: "Onshore Equipment Leaks / Fugitives",
  loading: "Loading Losses",
  separation: "Wastewater / Separation",
  chemical_production: "Chemical Production (Process CO₂)",
  nitric_acid_production: "Nitric Acid Production (Process N₂O)",
  adipic_acid_production: "Adipic Acid Production (Process N₂O)",
  asphalt_blowing: "Asphalt Blowing",
  indirect_steam: "Indirect Steam / Heat (Section 8)",
  cogen_allocation: "Cogeneration Allocation (Section 8)",
};

export const PROCESS_GROUPS = [
  {
    id: "Upstream",
    label: "Upstream (Exploration & Production)",
    options: [
      "associated_gas_venting",
      "drilling",
      "completions",
      "unloading",
      "combustion",
      "flaring",
      "routine_flaring",
      "non_routine_flaring",
      "safety_flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
      "separation",
    ],
  },
  {
    id: "Midstream",
    label: "Midstream (Processing & Transmission)",
    options: [
      "agr",
      "dehydrator",
      "combustion",
      "flaring",
      "routine_flaring",
      "non_routine_flaring",
      "safety_flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
    ],
  },
  {
    id: "Downstream",
    label: "Downstream (Refining & Distribution)",
    options: [
      "combustion",
      "flaring",
      "routine_flaring",
      "non_routine_flaring",
      "safety_flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
      "separation",
      "chemical_production",
      "nitric_acid_production",
      "adipic_acid_production",
      "asphalt_blowing",
    ],
  },
];
