/**
 * API Compendium Estimation of Greenhouse Gas Emissions
 * Standard Emission Factors
 * Ported from legacy emission-factors.js
 */

export const API_FACTORS = {
  // --- GASES ---
  "Natural Gas": {
    code: "NG",
    hhv: 1020, // Btu/scf
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    co: 0.04,
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "scf",
    // stream: "Upstream" - Removed to match all streams
  },
  "Natural Gas (Venting/Blowdown)": {
    code: "NG_Vent",
    co2: 0.054,
    ch4: 0.67,
    n2o: 0,
    co: 0,
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["venting"],
    stream: "Upstream",
    baseUnit: "scf",
  },
  "Landfill Gas": {
    code: "LFG",
    hhv: 500,
    co2: 52.07,
    ch4: 0.0032,
    n2o: 0.00063,
    co: 0.05,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "scf",
  },
  "Coke Oven Gas": {
    code: "COG",
    hhv: 590,
    co2: 46.85,
    ch4: 0.00048,
    n2o: 0.0001,
    co: 0.03,
    uncertainty: { co2: 0.02, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    stream: "Downstream",
    baseUnit: "scf",
  },
  "Blast Furnace Gas": {
    code: "BFG",
    hhv: 92,
    co2: 274.32,
    ch4: 0.000022,
    n2o: 0.0001,
    co: 0.02,
    uncertainty: { co2: 0.02, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Downstream",
  },
  "Propane (Gas)": {
    code: "LPG_Gas",
    hhv: 2500,
    co2: 61.46,
    ch4: 0.003,
    n2o: 0.0006,
    co: 0.03,
    uncertainty: { co2: 0.01, ch4: 0.2, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Downstream",
    baseUnit: "scf",
  },
  Acetylene: {
    code: "Acetylene",
    hhv: 1477, // Btu/scf
    co2: 73.0, // approx
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Propylene: {
    code: "Propylene",
    hhv: 2332,
    co2: 68.0,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Butane: {
    code: "Butane",
    hhv: 3280,
    co2: 65.0,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Isobutane: {
    code: "Isobutane",
    hhv: 3253,
    co2: 64.9,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion", "flaring"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  Naphtha: {
    code: "Naphtha",
    hhv: 5.24e6, // btu/bbl? need standardizing. Using per MMBtu factors usually.
    // API Compendium Table 3-8 default CO2 factors.
    co2: 68.02,
    ch4: 0.003,
    n2o: 0.0006,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "bbl",
  },
  "Compressed Natural Gas (CNG)": {
    code: "CNG",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Liquefied Natural Gas (LNG)": {
    code: "LNG",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },

  // --- FLARING-SPECIFIC GASES ---
  "Natural Gas (Flaring - Elevated)": {
    code: "NG_Flare_Elev",
    co2: 1.92,
    ch4: 0.012,
    n2o: 0.00001,
    co: 0.0035,
    combustionEfficiency: 0.98,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "API Compendium 2021 Section 3.3.2",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring - Ground)": {
    code: "NG_Flare_Ground",
    co2: 1.88,
    ch4: 0.024,
    n2o: 0.00001,
    co: 0.004,
    combustionEfficiency: 0.96,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "API Compendium 2021 Section 3.3.2",
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring - Enclosed)": {
    code: "NG_Flare_Enc",
    co2: 1.94,
    ch4: 0.006,
    n2o: 0.00001,
    co: 0.003,
    combustionEfficiency: 0.99,
    uncertainty: { co2: 0.02, ch4: 0.2, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    source: "API Compendium 2021 Section 3.3.2",
    baseUnit: "m3",
  },
  "Natural Gas (Flaring)": {
    code: "NG_Flare",
    co2: 1.92,
    ch4: 0.012,
    n2o: 0.00001,
    co: 0.0035,
    combustionEfficiency: 0.98,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Associated Gas (Flaring)": {
    code: "AG_Flare",
    co2: 2.15,
    ch4: 0.018,
    n2o: 0.00001,
    co: 0.004,
    uncertainty: { co2: 0.03, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Sour Gas (Flaring)": {
    code: "SG_Flare",
    co2: 2.3,
    ch4: 0.015,
    n2o: 0.00001,
    co: 0.0038,
    uncertainty: { co2: 0.03, ch4: 0.25, n2o: 0.5 },
    unit: "kg/m³",
    usage: ["flaring"],
    stream: "Upstream",
    baseUnit: "m3",
  },
  "Propane (Flaring)": {
    code: "LPG_Flare",
    co2: 63.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu", // Usually volume or energy? API varies. Sticking to energy/mass foundation.
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },
  "Butane (Flaring)": {
    code: "Butane_Flare",
    co2: 65.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },
  "Ethylene (Flaring)": {
    code: "Ethylene_Flare",
    co2: 69.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },
  "Propylene (Flaring)": {
    code: "Propylene_Flare",
    co2: 68.0,
    ch4: 0.003,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["flaring"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.5 },
    baseUnit: "scf",
  },

  // --- COMBUSTION - EQUIPMENT SPECIFIC (API Compendium Sec 4) ---
  "Natural Gas - 4-Stroke Lean Burn Engine": {
    code: "NG_4SLB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.3, // Example high methane slip: kg/MMBtu
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    description: "High CH4 Slip",
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.3 },
    baseUnit: "scf",
  },
  "Natural Gas - 4-Stroke Rich Burn Engine": {
    code: "NG_4SRB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001, // Controlled
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - 2-Stroke Lean Burn Engine": {
    code: "NG_2SLB",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.6, // Very high slip
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.3, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - Turbine": {
    code: "NG_Turbine",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.0037,
    n2o: 0.0013,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },
  "Natural Gas - Heater/Boiler": {
    code: "NG_Heater",
    hhv: 1020,
    co2: 53.06,
    ch4: 0.001,
    n2o: 0.0001,
    unit: "kg/MMBtu",
    usage: ["combustion"],
    uncertainty: { co2: 0.05, ch4: 0.2, n2o: 0.2 },
    baseUnit: "scf",
  },

  // --- LIQUIDS ---
  "Diesel (No. 2 Fuel Oil)": {
    code: "DSL",
    hhv: 138000,
    co2: 73.96,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream" - Removed to make available to Upstream Drilling
    baseUnit: "gal",
  },
  "Residual Fuel Oil (No. 6)": {
    code: "RFO",
    hhv: 150000,
    co2: 75.1,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  Kerosene: {
    code: "Kero",
    hhv: 135000,
    co2: 75.2,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Motor Gasoline": {
    code: "GAS",
    hhv: 125000,
    co2: 70.22,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Jet Fuel": {
    code: "JET",
    hhv: 135000,
    co2: 72.22,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  "Propane (Liquid)": {
    code: "LPG_Liq",
    hhv: 91500,
    co2: 62.88,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    // stream: "Downstream"
    baseUnit: "gal",
  },
  Ethane: {
    code: "Ethane",
    hhv: 69600,
    co2: 59.6,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    stream: "Midstream",
    baseUnit: "gal",
  },
  "Ethanol (100%)": {
    code: "EtOH",
    hhv: 84000,
    co2: 68.44,
    ch4: 0.0011,
    n2o: 0.0001,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    baseUnit: "gal",
  },
  "Biodiesel (100%)": {
    code: "BioDSL",
    hhv: 128000,
    co2: 73.84,
    ch4: 0.001,
    n2o: 0.0001,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion", "mobile"],
    baseUnit: "gal",
  },
  "Crude Oil": {
    code: "Crude",
    hhv: 138000,
    co2: 74.54,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },
  Lubricants: {
    code: "Lube",
    hhv: 144000,
    co2: 74.27,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },
  "Waste Oil": {
    code: "WasteOil",
    hhv: 138000,
    co2: 74.0,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.02, ch4: 0.25, n2o: 0.3 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "gal",
  },

  // --- SOLIDS ---
  "Anthracite Coal": {
    code: "CoalAnth",
    hhv: 25090,
    co2: 103.69,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Bituminous Coal": {
    code: "CoalBit",
    hhv: 24930,
    co2: 93.26,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Sub-Bituminous Coal": {
    code: "CoalSub",
    hhv: 17250,
    co2: 97.17,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Lignite Coal": {
    code: "CoalLig",
    hhv: 14210,
    co2: 97.72,
    ch4: 0.011,
    n2o: 0.0016,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Petroleum Coke": {
    code: "PetCoke",
    hhv: 30000,
    co2: 102.41,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  "Wood / Wood Waste": {
    code: "Wood",
    hhv: 8000,
    co2: 93.8,
    ch4: 0.0072,
    n2o: 0.0036,
    uncertainty: { co2: 0.05, ch4: 0.4, n2o: 0.5 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
    baseUnit: "ton",
  },
  Tires: {
    code: "Tires",
    hhv: 28000,
    co2: 85.97,
    ch4: 0.003,
    n2o: 0.0006,
    uncertainty: { co2: 0.03, ch4: 0.3, n2o: 0.4 },
    unit: "kg/MMBtu",
    usage: ["combustion"],
  },
  "Glycol Dehydrator": {
    code: "DEHY",
    co2: 0,
    ch4: 0,
    n2o: 0,
    unit: "hours",
    usage: ["dehydrator"],
    stream: "Midstream",
    uncertainty: { ch4: 0.5 },
  },
  "Desiccant Dehydrator": {
    code: "DehyDesiccant",
    ch4: 0,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["dehydrator"],
    description: "Desiccant Dehydrator (Batch)",
    uncertainty: { ch4: 0.5 },
  },

  // --- EQUIPMENT / SOURCE SPECIFIC (Added from Legacy) ---
  "Pneumatic Controller - High Bleed": {
    code: "HighBleed",
    ch4: 8.304,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Table 6-34 continuous bleed (gas processing)",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Controller - Low Bleed": {
    code: "LowBleed",
    ch4: 0.0939,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Table 6-34 pneumatic/hydraulic valve operator",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Controller - Intermittent": {
    code: "Intermittent",
    ch4: 0.4,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Table 6-42 intermittent vent controller",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Controller - Continuous Vent (T&S)": {
    code: "ContinuousVentTS",
    ch4: 3.5,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    description: "Table 6-42 continuous vent controller",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Pump - Chemical Injection (Piston)": {
    code: "PumpPiston",
    ch4: 2.65, // API 2021 Table 6-25
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Pump - Chemical Injection (Diaphragm)": {
    code: "PumpDiaphragm",
    ch4: 2.82, // API 2021 Table 6-25
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["pneumatic"],
    uncertainty: { ch4: 0.3 },
  },
  "Fugitive - Valve (Gas/Vapor)": {
    code: "ValveGas",
    // Mapping legacy factor to spec_ch4 for simplicity or generic factor
    // Legacy: factor: 0.0045 kg/hr/source.
    // We'll set spec_co2/ch4/n2o to 0 but maybe spec_ch4 if applicable?
    // Actually fugitive average factors are usually total hydrocarbon or methane?
    // Let's assume the factor is CH4 for now or strictly generic 'factor'.
    // For compliance, let's look at legacy: efFugitiveAverage returns tonnes_ch4/year.
    // So we should pre-calculate or provide the raw CH4 factor.
    // Legacy efFugitiveAverage for Gas Valves = 0.026 tonnes CH4/year.
    ch4: 0.026,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Gas Service",
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Connector (Gas/Vapor)": {
    code: "ConnGas",
    ch4: 0.003,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Gas Service",
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Flange (Gas/Vapor)": {
    code: "FlangeGas",
    ch4: 0.003,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Gas Service",
    uncertainty: { ch4: 0.5 },
  },
  // --- API 2021 ADDITIONAL FUGITIVES ---
  "Fugitive - Valve (Light Oil)": {
    code: "ValveLightOil",
    ch4: 0.0019, // Derived from Total HC * %CH4 for light oil if available, or use API average
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Light Oil Service",
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Valve (Heavy Oil)": {
    code: "ValveHeavyOil",
    ch4: 0.00003, // Very low CH4 content typically
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Heavy Oil Service",
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Connector (Light Oil)": {
    code: "ConnLightOil",
    ch4: 0.0002,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Light Oil Service",
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Connector (Heavy Oil)": {
    code: "ConnHeavyOil",
    ch4: 0.00001,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    description: "Average Factor - Heavy Oil Service",
    uncertainty: { ch4: 0.5 },
  },
  // --- ADDITIONAL FUGITIVES (Seals, OEL, PRV) ---
  "Fugitive - Open-Ended Line (Gas)": {
    code: "OELGas",
    ch4: 0.019,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Open-Ended Line (Light Oil)": {
    code: "OELLightOil",
    ch4: 0.002,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Pressure Relief Valve (Gas)": {
    code: "PRVGas",
    ch4: 0.061,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Pressure Relief Valve (Light Oil)": {
    code: "PRVLightOil",
    ch4: 0.012,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Compressor Seal (Centrifugal - Wet)": {
    code: "CompSealCentWet",
    ch4: 0.047,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Compressor Seal (Centrifugal - Dry)": {
    code: "CompSealCentDry",
    ch4: 0.027,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Compressor Seal (Reciprocating)": {
    code: "CompSealRecip",
    ch4: 0.076,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Pump Seal (Gas)": {
    code: "PumpSealGas",
    ch4: 0.024,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Pump Seal (Light Oil)": {
    code: "PumpSealLightOil",
    ch4: 0.013,
    co2: 0,
    n2o: 0,
    unit: "tonnes/yr",
    usage: ["fugitive"],
    uncertainty: { ch4: 0.5 },
  },
  // --- PIPELINE FUGITIVES ---
  "Fugitive - Pipeline Leaks (Gas)": {
    code: "PipeLeakGas",
    ch4: 0.05, // Placeholder factor (tonnes/km-year) based on general transmission data
    co2: 0,
    n2o: 0,
    unit: "tonnes/km-year",
    usage: ["fugitive_pipeline"],
    description: "Average fugitive emissions per km of gas pipeline",
    uncertainty: { ch4: 0.5 },
  },
  "Fugitive - Pipeline Leaks (Oil)": {
    code: "PipeLeakOil",
    ch4: 0.0002, // Very low for oil lines
    co2: 0,
    n2o: 0,
    unit: "tonnes/km-year",
    usage: ["fugitive_pipeline"],
    description: "Average fugitive emissions per km of oil pipeline",
    uncertainty: { ch4: 0.5 },
  },

  "Methane Flashing - Crude Oil (Small Tank)": {
    code: "TankCrudeSmall",
    ch4: 0.18,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "API Table 6-4: <= 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Crude Oil (Large Tank)": {
    code: "TankCrudeLarge",
    ch4: 0.12,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "API Table 6-4: > 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Production Condensate (Small Tank)": {
    code: "TankProdSmall",
    ch4: 1.56,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "API Table 6-4: <= 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Production Condensate (Large Tank)": {
    code: "TankProdLarge",
    ch4: 1.16,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "API Table 6-4: > 10 bbl/d",
    uncertainty: { ch4: 0.4 },
  },
  "Methane Flashing - Produced Water (Tank)": {
    code: "TankWater",
    ch4: 0.01,
    co2: 0,
    n2o: 0,
    unit: "kg CH4/bbl",
    usage: ["tank"],
    description: "Atmospheric Tank - Produced Water",
    uncertainty: { ch4: 0.4 },
  },
  // --- COMPLETIONS / UNLOADING (Tier 1 Defaults) ---
  "Completion - Gas Well (No Flaring)": {
    code: "CompGasNoFlare",
    ch4: 0.7, // Approx placeholder (700 kg/event?) - adjusting to tonnes
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["completions"],
    description: "Average per event (Uncontrolled)",
    uncertainty: { ch4: 0.3 },
  },
  "Workover - Gas Well (No Flaring)": {
    code: "WorkoverGasNoFlare",
    ch4: 0.05,
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["completions"],
    description: "Average per event (Uncontrolled)",
    uncertainty: { ch4: 0.3 },
  },
  "Liquids Unloading - Plunger Lift": {
    code: "UnloadPlunger",
    ch4: 0.1, // Placeholder average
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["unloading"],
    description: "Average per event",
    uncertainty: { ch4: 0.25 },
  },
  "Liquids Unloading - Non-Plunger": {
    code: "UnloadNonPlunger",
    ch4: 0.2, // Placeholder average
    co2: 0,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["unloading"],
    description: "Average per event",
    uncertainty: { ch4: 0.25 },
  },
  "Drilling - Mud Degassing (Water Based)": {
    code: "MudWater",
    ch4: 0.18,
    co2: 0,
    n2o: 0,
    uncertainty: { ch4: 0.5 },
    unit: "kg CH4/bbl mud",
    baseUnit: "bbl",
    usage: ["drilling"],
    description: "Water Based Mud",
  },
  "Drilling - Mud Degassing (Oil Based)": {
    code: "MudOil",
    ch4: 37.5,
    co2: 0,
    n2o: 0,
    uncertainty: { ch4: 0.5 },
    unit: "kg CH4/bbl mud",
    baseUnit: "bbl",
    usage: ["drilling"],
    description: "Oil Based Mud (Diesel)",
  },

  "Dehydrator - Glycol (Uncontrolled)": {
    code: "DehyUncont",
    // API Compendium 5.3: ~0.82 kg CH4 per MMscf throughput → 0.00082 tonnes/MMscf
    ch4: 0.00082,
    co2: 0,
    n2o: 0,
    unit: "tonnes/MMscf",
    baseUnit: "MMscf",
    usage: ["dehydrator"],
    description: "Glycol Dehydrator Venting (Uncontrolled)",
    uncertainty: { ch4: 0.5 },
  },
  "Dehydrator - Glycol (Controlled)": {
    code: "DehyCont",
    // Controlled: ~90% reduction from uncontrolled
    ch4: 0.000082,
    co2: 0,
    n2o: 0,
    unit: "tonnes/MMscf",
    baseUnit: "MMscf",
    usage: ["dehydrator"],
    description: "Glycol Dehydrator Venting (w/ Emission Control)",
    uncertainty: { ch4: 0.5 },
  },
  // --- ACID GAS REMOVAL (AGR) ---
  "Amine Unit - Venting (Generic)": {
    code: "AmineVent",
    ch4: 0.026, // Placeholder based on API/GRI generic if specific data missing
    co2: 1.1, // Varies heavily by gas composition (tonnes/MMscf throughput?)
    n2o: 0,
    unit: "tonnes/MMscf",
    usage: ["agr"],
    description: "Amine Unit Venting (Default)",
    uncertainty: { co2: 0.3, ch4: 0.5 },
  },

  // --- LOADING LOSSES (API Section 5.2) ---
  "Loading - Crude Oil (Tank Truck)": {
    code: "LoadCrudeTruck",
    ch4: 0.00016, // Factor from API: ~1.6 lb/1000 gal -> converted to kg/bbl or similar?
    // API Table 5-12: Submerged loading: 2.1 lb/1000 gal VOC. CH4 fraction small.
    // Using simplified default for now: kg/bbl
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    description: "Truck Loading (Submerged)",
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Crude Oil (Rail)": {
    code: "LoadCrudeRail",
    ch4: 0.00016,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Crude Oil (Marine Vessel)": {
    code: "LoadCrudeMarine",
    ch4: 0.00008, // API Marine typically lower loss rates
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Condensate (Tank Truck)": {
    code: "LoadCondTruck",
    ch4: 0.0005, // Higher volatility
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },
  "Loading - Gasoline (Tank Truck)": {
    code: "LoadGasTruck",
    ch4: 0.0, // Mostly VOCs, practically zero CH4?
    // API says Gasoline vapor is VOC. But for completeness we track.
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["loading"],
    uncertainty: { ch4: 0.3 },
  },

  // --- WASTEWATER / SEPARATION ---
  "Separator Venting - Gas Well": {
    code: "SepVentGas",
    ch4: 0.058,
    co2: 0.003,
    n2o: 0,
    unit: "kg/m3",
    baseUnit: "m3",
    usage: ["separation"],
    description: "Separator vent losses (gas well service)",
    uncertainty: { co2: 0.3, ch4: 0.4 },
  },
  "Separator Venting - Oil Well": {
    code: "SepVentOil",
    ch4: 0.012,
    co2: 0.001,
    n2o: 0,
    unit: "kg/m3",
    baseUnit: "m3",
    usage: ["separation"],
    description: "Separator vent losses (oil well service)",
    uncertainty: { co2: 0.3, ch4: 0.4 },
  },
  "Wastewater - CH4 (Open System)": {
    code: "WastewaterCH4",
    ch4: 0.0006,
    co2: 0,
    n2o: 0,
    unit: "kg/m3",
    baseUnit: "m3",
    usage: ["separation"],
    description: "Produced water / wastewater open system (API 5.4)",
    uncertainty: { ch4: 0.5 },
  },
  "Wastewater - Oil/Water Separator": {
    code: "WaterSep",
    ch4: 0.0005,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl water",
    baseUnit: "bbl",
    usage: ["separation"],
    description: "API Section 5.4 Separator",
    uncertainty: { ch4: 0.5 },
  },

  // --- BLOWDOWN / VENTING DETAILED ---
  "Blowdown - Compressor (Reciprocating)": {
    code: "BlowdownCompRecip",
    ch4: 0.15, // tonnes/event default? or m3?
    co2: 0.01,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["venting"],
    uncertainty: { ch4: 0.4, co2: 0.2 },
  },
  "Blowdown - Compressor (Centrifugal)": {
    code: "BlowdownCompCent",
    ch4: 0.25,
    co2: 0.01,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["venting"],
    uncertainty: { ch4: 0.4, co2: 0.2 },
  },
  "Blowdown - Pipeline": {
    code: "BlowdownPipe",
    ch4: 1.5,
    co2: 0.05,
    n2o: 0,
    unit: "tonnes/event",
    usage: ["venting"],
    description: "Generic Pipeline Blowdown",
    uncertainty: { ch4: 0.4, co2: 0.2 },
  },

  // --- DEHYDRATORS (API Section 5.3) ---
  "Dehydrator - TEG (No Controls)": {
    code: "DehydTEGNoCtrl",
    ch4: 37.85,
    co2: 0,
    n2o: 0,
    unit: "scf/gal TEG",
    usage: ["dehydrator"],
    description: "API 5.3 - TEG Dehydrator without emission controls",
    uncertainty: { ch4: 0.5 },
  },
  "Dehydrator - TEG (Flash Tank)": {
    code: "DehydTEGFlash",
    ch4: 15.14,
    co2: 0,
    n2o: 0,
    unit: "scf/gal TEG",
    usage: ["dehydrator"],
    description: "API 5.3 - TEG Dehydrator with flash tank separator",
    uncertainty: { ch4: 0.5 },
  },
  "Dehydrator - TEG (Condenser)": {
    code: "DehydTEGCond",
    ch4: 3.785,
    co2: 0,
    n2o: 0,
    unit: "scf/gal TEG",
    usage: ["dehydrator"],
    description: "API 5.3 - TEG Dehydrator with condenser",
    uncertainty: { ch4: 0.5 },
  },

  // --- PNEUMATIC DEVICES (API Section 5.2) ---
  "Pneumatic Device - High Bleed": {
    code: "PneumHighBleed",
    ch4: 37.3,
    co2: 0,
    n2o: 0,
    unit: "scf/hr/device",
    usage: ["pneumatic"],
    description: "API 5.2 - High-bleed pneumatic device",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Device - Low Bleed": {
    code: "PneumLowBleed",
    ch4: 1.39,
    co2: 0,
    n2o: 0,
    unit: "scf/hr/device",
    usage: ["pneumatic"],
    description: "API 5.2 - Low-bleed pneumatic device",
    uncertainty: { ch4: 0.3 },
  },
  "Pneumatic Device - Intermittent": {
    code: "PneumIntermit",
    ch4: 13.5,
    co2: 0,
    n2o: 0,
    unit: "scf/year/device",
    usage: ["pneumatic"],
    description: "API 5.2 - Intermittent bleed pneumatic device",
    uncertainty: { ch4: 0.3 },
  },

  // --- STORAGE TANKS (API Section 4.4) ---
  "Tank - Flash Emissions (Oil)": {
    code: "TankFlashOil",
    ch4: 0.193,
    co2: 0.012,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["tank_flashing"],
    description: "API Table 5-16 / 6-4 — Default crude oil flash emission factor",
    uncertainty: { ch4: 0.4, co2: 0.15 },
  },
  "Tank - Working Losses (Oil)": {
    code: "TankWorkOil",
    ch4: 0.05,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl",
    usage: ["tank_working"],
    description: "API 4.4 - Working losses",
    uncertainty: { ch4: 0.4 },
  },
  "Tank - Breathing Losses (Oil)": {
    code: "TankBreathOil",
    ch4: 0.001,
    co2: 0,
    n2o: 0,
    unit: "kg/bbl-year",
    usage: ["tank_breathing"],
    description: "API 4.4 - Standing storage breathing losses",
    uncertainty: { ch4: 0.4 },
  },

  // --- CHEMICAL PRODUCTION (API Section 6, Table 6-167) ---
  "Acrylonitrile": {
    code: "ACN_Prod",
    co2: 1.00,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "API Section 6 Table 6-167 — Acrylonitrile process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Carbon Black": {
    code: "CB_Prod",
    co2: 2.63,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "API Section 6 Table 6-167 — Carbon Black process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Ethylene": {
    code: "ETH_Prod",
    co2: 0.77,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "API Section 6 Table 6-167 — Ethylene process CO₂",
    uncertainty: { co2: 0.10 },
  },
  "Ethylene Dichloride": {
    code: "EDC_Prod",
    co2: 0.041,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "API Section 6 Table 6-167 — EDC process CO₂",
    uncertainty: { co2: 0.15 },
  },
  "Ethylene Oxide": {
    code: "ETO_Prod",
    co2: 0.46,
    ch4: 0,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "API Section 6 Table 6-167 — Ethylene Oxide process CO₂",
    uncertainty: { co2: 0.10 },
  },
  "Methanol": {
    code: "MEOH_Prod",
    co2: 0.67,
    ch4: 0.0023,
    n2o: 0,
    unit: "tonne CO₂/tonne product",
    usage: ["chemical_production"],
    description: "API Section 6 Table 6-167 — Methanol process CO₂ + CH₄",
    uncertainty: { co2: 0.10, ch4: 0.20 },
  },

  // --- NITRIC ACID N₂O (API Section 6, pg 407) ---
  "Nitric Acid - With NSCR": {
    code: "HNO3_NSCR",
    co2: 0,
    ch4: 0,
    n2o: 2.0,
    unit: "kg N₂O/tonne product",
    usage: ["nitric_acid_production"],
    description: "API Section 6 pg 407 — Nitric acid with NSCR abatement",
    uncertainty: { n2o: 0.10 },
  },
  "Nitric Acid - Without NSCR": {
    code: "HNO3_NoNSCR",
    co2: 0,
    ch4: 0,
    n2o: 9.0,
    unit: "kg N₂O/tonne product",
    usage: ["nitric_acid_production"],
    description: "API Section 6 pg 407 — Nitric acid without NSCR abatement",
    uncertainty: { n2o: 0.20 },
  },

  // --- ADIPIC ACID N₂O (API Section 6, pg 407) ---
  "Adipic Acid - Thermal Abatement": {
    code: "AA_Thermal",
    co2: 0,
    ch4: 0,
    n2o: 13.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "API Section 6 pg 407 — Adipic acid with thermal abatement",
    uncertainty: { n2o: 0.10 },
  },
  "Adipic Acid - Catalytic Abatement": {
    code: "AA_Catalytic",
    co2: 0,
    ch4: 0,
    n2o: 53.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "API Section 6 pg 407 — Adipic acid with catalytic abatement",
    uncertainty: { n2o: 0.15 },
  },
  "Adipic Acid - Uncontrolled": {
    code: "AA_Uncontrolled",
    co2: 0,
    ch4: 0,
    n2o: 300.0,
    unit: "kg N₂O/tonne product",
    usage: ["adipic_acid_production"],
    description: "API Section 6 pg 407 — Adipic acid uncontrolled",
    uncertainty: { n2o: 0.30 },
  },

  // --- ASPHALT BLOWING (API Section 6, Table 6-52) ---
  "Asphalt": {
    code: "ASPH_Blow",
    co2: 10.4326,
    ch4: 0.02268,
    n2o: 0,
    unit: "kg/ton",
    usage: ["asphalt_blowing"],
    description: "API Section 6 Table 6-52 — Asphalt blowing process emissions",
    uncertainty: { co2: 0.30, ch4: 0.30 },
  },
};
export const PROCESS_TYPES = {
  combustion: "Stationary Combustion",
  flaring: "Flaring",
  venting: "Venting (Blowdown)",
  pneumatic: "Pneumatic Device",
  tank_flashing: "Storage Tank - Flashing/Events",
  tank_working: "Storage Tank - Working Losses",
  tank_breathing: "Storage Tank - Breathing Losses",
  drilling: "Drilling Operations",
  completions: "Well Completions & Workovers",
  unloading: "Liquids Unloading",
  agr: "Acid Gas Removal (AGR)",
  dehydrator: "Dehydrator",
  mobile: "Mobile Combustion",
  fugitive: "Fugitive Emissions",
  loading: "Loading Losses",
  separation: "Wastewater / Separation",
  chemical_production: "Chemical Production (Process CO₂)",
  nitric_acid_production: "Nitric Acid Production (Process N₂O)",
  adipic_acid_production: "Adipic Acid Production (Process N₂O)",
  asphalt_blowing: "Asphalt Blowing",
  indirect_steam: "Indirect Steam / Heat (Section 8)",
  cogen_allocation: "Cogeneration Allocation (Section 8)",
};

export const PROCESS_GROUPS = [
  {
    id: "Upstream",
    label: "Upstream (Exploration & Production)",
    options: [
      "drilling",
      "completions",
      "unloading",
      "combustion",
      "flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
      "separation",
    ],
  },
  {
    id: "Midstream",
    label: "Midstream (Processing & Transmission)",
    options: [
      "agr",
      "dehydrator",
      "combustion",
      "flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
    ],
  },
  {
    id: "Downstream",
    label: "Downstream (Refining & Distribution)",
    options: [
      "combustion",
      "flaring",
      "venting",
      "pneumatic",
      "tank_flashing",
      "tank_working",
      "tank_breathing",
      "mobile",
      "fugitive",
      "loading",
      "separation",
      "chemical_production",
      "nitric_acid_production",
      "adipic_acid_production",
      "asphalt_blowing",
    ],
  },
];
