import { launch, session, shot, UI, sleep, dashboard } from "./lib.mjs";
const b = await launch(); const { page, log } = await session(b, "admin");
let d = await dashboard(page, log, { year: "2025", region: "AUDIT-L Plant" });
const g = t => { const i = t.indexOf("GROSS OPERATIONAL"); return t.slice(i, i + 330).replace(/\n+/g, " | "); };
console.log("GWP100:", g(d.txt));
const n0 = log.api.length;
await page.getByText("GWP-20", { exact: true }).first().click(); await sleep(4000);
const t = await page.locator("main, body").first().innerText();
console.log("GWP20:", g(t));
console.log("calls after toggle:", log.api.slice(n0).map(a => `${a.status} ${a.url}`).join("\n"));
const bb = [...log.api].reverse().find(a => a.url.includes("batch-all"));
console.log("summary:", JSON.stringify(bb.body.summary));
await page.reload(); await sleep(4000);
const t2 = await page.locator("main, body").first().innerText();
console.log("after reload GWP20 still active?", g(t2).slice(0, 120), "| toggle classes:", await page.getByText("GWP-20", { exact: true }).first().getAttribute("class"));
await shot(page, "w10_gwp20", true);
await b.close();
