import { launch, session, shot, sleep, dashboard } from "./lib.mjs";
const b = await launch();
const { page, log } = await session(b, process.argv[4] || "admin");
const { txt, batch } = await dashboard(page, log, { year: process.argv[2] || "2025", region: process.argv[3] || "AUDIT-L Plant" });
const i = txt.indexOf("EMISSIONS OVERVIEW");
console.log(txt.slice(i, i + 900).replace(/\n+/g, " | "));
console.log("BATCH URL", batch?.url);
const bb = batch?.body || {};
console.log("BATCH keys", Object.keys(bb));
console.log(JSON.stringify(bb).slice(0, 3000));
await shot(page, "w3_dash", true);
console.log("ERR", log.errors.slice(1, 5));
await b.close();
