import { launch, session, shot, UI, sleep, openS1, fillS1, submitS1, toasts } from "./lib.mjs";
const b = await launch();
const u = await session(b, "user");
await openS1(u.page);
const fac = await u.page.locator(".custom-dropdown .dropdown-selected").first().click().then(() => sleep(400)).then(() => u.page.locator(".dropdown-portal .dropdown-option").allInnerTexts());
console.log("user sees", fac.length - 1, "facilities:", fac.slice(0, 12).join(" ; "));
await u.page.mouse.click(5, 500);
await fillS1(u.page, { facility: "AUDIT-L Plant", year: 2025, month: 7, factor: "Diesel (No. 2 Fuel Oil)", qty: 1000, unit: "gal" });
const r = await submitS1(u.page, u.log);
console.log("USER POST", r?.status, JSON.stringify(r?.body).slice(0, 600));
console.log("toast", await toasts(u.page));
await shot(u.page, "w4_user_after", true);
await b.close();
