import { launch, session, sleep, openS1, fillS1, submitS1 } from "./lib.mjs";
const b = await launch();
const a = await session(b, "admin"); const u = await session(b, "user");
const q = async () => a.page.evaluate(async () => (await (await fetch("/api/dashboard/batch-all?facilityId=173&activity=all&division=all&year=2025", { credentials: "include" })).json()).pending_stats);
console.log("before", JSON.stringify(await q()));
await openS1(u.page);
await fillS1(u.page, { facility: "AUDIT-L Plant", year: 2025, month: 8, factor: "Diesel (No. 2 Fuel Oil)", qty: 500, unit: "gal" });
const r = await submitS1(u.page, u.log); console.log("user POST", r?.status, r?.body?.id);
console.log("after", JSON.stringify(await q()));
await sleep(5000); console.log("after+5s", JSON.stringify(await q()));
await b.close();
