import { launch, session, sleep, openS1 } from "./lib.mjs";
const b = await launch(); const { page, log } = await session(b, "user");
await openS1(page); await sleep(2000);
const rows = await page.locator("tr", { hasText: "AUDIT-L" }).allInnerTexts();
console.log(rows.map(r => r.replace(/\s+/g, " ")).join("\n"));
const e = [...log.api].reverse().find(a => /\/api\/emissions\?|\/api\/emissions\/?$/.test(a.url) && a.method === "GET");
console.log("list api", e?.url, JSON.stringify(e?.body).slice(0, 300));
const n = [...log.api].reverse().find(a => a.url.includes("/api/notifications") && a.body);
console.log("notifs", JSON.stringify(n?.body).slice(0, 600));
await b.close();
