import { launch, session, shot, UI, sleep, openS1, dashboard, toasts } from "./lib.mjs";
const b = await launch(); const { page, log } = await session(b, "admin");
const kpi = async () => { const d = await dashboard(page, log, { year: "2025", region: "AUDIT-L Plant" }); const s = d.batch?.body?.summary?.[0] || {}; const t = d.txt; const i = t.indexOf("GROSS OPERATIONAL"); return `UI: ${t.slice(i, i + 60).replace(/\n+/g, " ")} | API s1=${s.scope1_total} s2=${s.scope2_total}`; };
console.log("BEFORE", await kpi());
await openS1(page); await sleep(1500);
const row = page.locator("tr", { hasText: "500.00 gal" }).filter({ hasText: "AUDIT-L" }).first();
console.log("row:", (await row.innerText()).replace(/\s+/g, " ").slice(0, 150));
console.log("row buttons:", await row.locator("button").evaluateAll(bs => bs.map(b => b.title || b.innerText || b.className)));
await row.locator("button[title*=elete], button.delete-btn, button:has-text('Delete')").first().click(); await sleep(1000);
await shot(page, "w9_confirm");
const n0 = log.api.length;
await page.getByRole("button", { name: /^(Delete|Confirm|Yes)/ }).last().click(); await sleep(3000);
console.log("calls:", log.api.slice(n0).filter(a => a.method === "DELETE").map(a => `${a.status} ${a.url} ${JSON.stringify(a.body)}`), "toast:", (await toasts(page)).replace(/\s+/g, " ").slice(0, 100));
await page.reload(); await sleep(3000);
console.log("row still listed after reload:", await page.locator("tr", { hasText: "500.00 gal" }).filter({ hasText: "AUDIT-L" }).count());
console.log("AFTER", await kpi());
await b.close();
