import { pathToFileURL } from "url";
import fs from "fs";
const CLIENT = "C:/Users/samsung/Desktop/H2/new/client";
const { chromium } = await import(pathToFileURL(CLIENT + "/node_modules/playwright/index.mjs").href);
const browser = await chromium.launch({ executablePath: process.env.USERPROFILE + "/AppData/Local/ms-playwright/chromium-1208/chrome-win64/chrome.exe" });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const apis = [];
page.on("response", async r => { if (r.url().includes("/api/")) { try { const t = await r.text(); apis.push({url: r.url(), status: r.status(), body: t.slice(0, 200000)}); } catch {} } });
await page.goto("http://127.0.0.1:5192/login"); const skip = page.locator(".skip-intro-btn"); if (await skip.count()) await skip.click().catch(()=>{});
await page.fill('input[placeholder="Email Address"]', "audit_admin@audit.local");
await page.fill('input[type="password"]', "AuditPass!2026");
await page.keyboard.press("Enter");
await page.waitForTimeout(3000);
const path = process.argv[2] || "/dashboard";
await page.goto("http://127.0.0.1:5192/" + path);
await page.waitForTimeout(8000);
const name = process.argv[3] || "dash";
await page.screenshot({ path: name + ".png", fullPage: true });
fs.writeFileSync(name + "_text.txt", await page.evaluate(() => document.body.innerText));
fs.writeFileSync(name + "_apis.json", JSON.stringify(apis, null, 1));
await browser.close();
