import { pathToFileURL } from "url"; import fs from "fs";
const CLIENT = "C:/Users/samsung/Desktop/H2/new/client";
const { chromium } = await import(pathToFileURL(CLIENT + "/node_modules/playwright/index.mjs").href);
const browser = await chromium.launch({ executablePath: process.env.USERPROFILE + "/AppData/Local/ms-playwright/chromium-1208/chrome-win64/chrome.exe" });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto("http://127.0.0.1:5192/login"); const skip = page.locator(".skip-intro-btn"); if (await skip.count()) await skip.click().catch(()=>{});
await page.fill('input[placeholder="Email Address"]', "audit_admin@audit.local");
await page.fill('input[type="password"]', "AuditPass!2026"); await page.keyboard.press("Enter");
await page.waitForTimeout(3000); await page.goto("http://127.0.0.1:5192/dashboard"); await page.waitForTimeout(7000);
const grab = async (tag) => {
  const t = await page.evaluate(() => { const q=s=>[...document.querySelectorAll(s)].map(e=>e.innerText.replace(/\n/g,' ')); return {hero:q('.stat-item'), pills:q('.scope-pill'), flare:q('.flaring-stream-item'), banner:q('.pending-banner-desc'), table:q('.data-table tr').slice(0,14)}; });
  fs.writeFileSync(`ui_${tag}.json`, JSON.stringify(t,null,1)); await page.screenshot({path:`ui_${tag}.png`}); console.log(tag, JSON.stringify(t.hero), JSON.stringify(t.pills));
};
await grab("default");
const pick = async (cur, val) => { await page.locator(".custom-dropdown .dropdown-selected", {hasText: cur}).first().click(); await page.waitForTimeout(500); await page.locator(".dropdown-option", {hasText: val}).first().click(); };
await pick("All Years","2025"); await page.waitForTimeout(5000); await grab("y2025");
await page.click("text=GWP-20"); await page.waitForTimeout(5000); await grab("y2025_gwp20");
await page.click("text=GWP-100"); await page.waitForTimeout(3000);
await page.locator(".pending-switch").click(); await page.waitForTimeout(5000); await grab("y2025_pending");
await page.locator(".pending-switch").click(); await page.waitForTimeout(3000);
await pick("2025","All Years"); await page.waitForTimeout(4000); await pick("All Supply Chains","Heavy Industry"); await page.waitForTimeout(5000); await grab("seg_heavy");
await pick("Heavy Industry","All Supply Chains"); await page.waitForTimeout(3000); await pick("All Activities","Steel"); await page.waitForTimeout(5000); await grab("act_steel");
await browser.close();
