// System fields each bulk-import type accepts: { id, label, required, hint }.
export const TEMPLATES = {
  sources: [
    {
      id: "activity",
      label: "Activity",
      required: false,
      hint: "e.g. Exploration & Production",
    },
    {
      id: "division",
      label: "Division",
      required: false,
      hint: "e.g. Production, Association",
    },
    {
      id: "facility_id",
      label: "Region",
      required: true,
      hint: "e.g. Hassi Messaoud",
    },
    { id: "field", label: "Field", required: false },
    { id: "name", label: "Equipment Name", required: true },
    { id: "equipment_id", label: "Equipment ID", required: false },
    {
      id: "type",
      label: "Process Type",
      required: false,
      hint: "e.g. combustion, flaring",
    },
    {
      id: "fuel_type",
      label: "Fuel Type",
      required: false,
      hint: "e.g. Natural Gas",
    },
    { id: "design_capacity", label: "Design Capacity", required: false },
    { id: "installation_date", label: "Installation Date", required: false, hint: "YYYY-MM-DD" },
    { id: "status", label: "Status", required: false, hint: "Active / Inactive" },
  ],
  activity: [
    { id: "activity", label: "Activity", required: false },
    { id: "division", label: "Division", required: false },
    { id: "facility_id", label: "Region", required: true },
    { id: "facility_name", label: "Region / Facility", required: false },
    { id: "field", label: "Field", required: false },
    { id: "group", label: "Emission Source (Group)", required: false },
    { id: "equipment", label: "Equipment Name", required: false },
    { id: "equipment_id", label: "Equipment ID", required: false },
    { id: "year", label: "Year", required: false },
    { id: "month", label: "Month", required: false },
    { id: "date", label: "Date", required: true },
    { id: "process", label: "Process Type", required: true },
    { id: "process_type", label: "Process Type (legacy)", required: false },
    { id: "fuel", label: "Activity / Fuel", required: false, hint: "Emission factor name (default and custom rows)" },
    { id: "fuel_type", label: "Fuel Type (legacy)", required: false },
    { id: "quantity", label: "Quantity", required: true },
    { id: "amount", label: "Amount", required: false },
    { id: "unit", label: "Unit", required: true },
    { id: "factor_type", label: "Factor Type", required: false },
    { id: "hhv", label: "HHV", required: false },
    { id: "ef_unit", label: "EF Unit", required: false },
    { id: "combustion_efficiency", label: "Combustion Eff", required: false },
    { id: "flare_type", label: "Flare Type", required: false },
    { id: "ch4_content", label: "CH4 Content %", required: false },
    { id: "co2_content", label: "CO2 Content %", required: false },
    { id: "control_efficiency", label: "Control Eff", required: false },
    { id: "operating_temperature", label: "Op Temp", required: false },
    { id: "temp_unit", label: "Temp Unit", required: false },
    { id: "operating_pressure", label: "Op Press", required: false },
    { id: "press_unit", label: "Press Unit", required: false },
    { id: "z_factor", label: "Z Factor", required: false },
    { id: "c1", label: "C1", required: false },
    { id: "c2", label: "C2", required: false },
    { id: "c3", label: "C3", required: false },
    { id: "c4", label: "C4", required: false },
    { id: "c5", label: "C5", required: false },
    { id: "c6", label: "C6", required: false },
    { id: "c7", label: "C7", required: false },
    { id: "c8", label: "C8", required: false },
    { id: "c9", label: "C9", required: false },
    { id: "c10", label: "C10+", required: false },
    { id: "co2_mol", label: "CO2 Mol %", required: false },
    { id: "n2_mol", label: "N2 Mol %", required: false },
    { id: "mud_type", label: "Mud Type", required: false },
    { id: "mud_unit", label: "Mud Unit", required: false },
    { id: "comp_method", label: "Comp Method", required: false },
    { id: "comp_rate", label: "Comp Rate", required: false },
    { id: "comp_duration", label: "Comp Duration", required: false },
    { id: "comp_flare_eff", label: "Comp Flare Eff", required: false },
    { id: "unload_depth", label: "Unload Depth", required: false },
    { id: "unload_diam", label: "Unload Diam", required: false },
    { id: "unload_press", label: "Unload Press", required: false },
    { id: "unload_freq", label: "Unload Freq", required: false },
    { id: "unload_flare_eff", label: "Unload Flare Eff", required: false },
    { id: "unload_temp", label: "Unload Temp", required: false },
    { id: "blowdown_pressure", label: "BD Press", required: false },
    { id: "blowdown_events", label: "BD Events", required: false },
    { id: "blowdown_temp", label: "BD Temp", required: false },
    { id: "blowdown_temp_unit", label: "BD Temp Unit", required: false },
    { id: "blowdown_press_unit", label: "BD Press Unit", required: false },
    { id: "tank_gor", label: "Tank GOR", required: false },
    { id: "tank_control_eff", label: "Tank Control Eff", required: false },
    { id: "tank_unit", label: "Tank Unit", required: false },
    { id: "tank_api_gravity", label: "Tank API Gravity", required: false },
    { id: "tank_throughput", label: "Tank Throughput", required: false },
    { id: "tank_throughput_unit", label: "Tank Thr Unit", required: false },
    { id: "tank_turnovers", label: "Tank Turnovers", required: false },
    { id: "pneu_type", label: "Pneu Type", required: false },
    { id: "pneu_count", label: "Pneu Count", required: false },
    { id: "pneu_bleed_rate", label: "Pneu Bleed Rate", required: false },
    { id: "pneu_hours", label: "Pneu Hours", required: false },
    { id: "pump_type", label: "Pump Type", required: false },
    { id: "pump_count", label: "Pump Count", required: false },
    { id: "pump_gas_rate", label: "Pump Gas Rate", required: false },
    { id: "pump_hours", label: "Pump Hours", required: false },
    { id: "comp_mode", label: "Comp Mode", required: false },
    { id: "comp_hours", label: "Comp Hours", required: false },
    { id: "comp_count", label: "Comp Count", required: false },
    { id: "operating_hours", label: "Op Hours", required: false },
    { id: "leak_count", label: "Leak Count", required: false },
    { id: "leak_duration", label: "Leak Duration", required: false },
    { id: "leak_rate", label: "Leak Rate", required: false },
    { id: "agr_throughput", label: "AGR Throughput", required: false },
    { id: "agr_co2_in", label: "AGR CO2 In", required: false },
    { id: "agr_co2_out", label: "AGR CO2 Out", required: false },
    { id: "agr_unit", label: "AGR Unit", required: false },
    { id: "agr_ch4_in", label: "AGR CH4 In", required: false },
    { id: "agr_ch4_slip", label: "AGR CH4 Slip", required: false },
    { id: "agr_control_eff", label: "AGR Control Eff", required: false },
    { id: "dehy_pump_rate", label: "Dehy Pump Rate", required: false },
    { id: "dehy_pump_unit", label: "Dehy Pump Unit", required: false },
    { id: "dehy_hours", label: "Dehy Hours", required: false },
    { id: "dehy_press", label: "Dehy Press", required: false },
    { id: "dehy_press_unit", label: "Dehy Press Unit", required: false },
    { id: "dehy_temp", label: "Dehy Temp", required: false },
    { id: "dehy_temp_unit", label: "Dehy Temp Unit", required: false },
    { id: "dehy_has_flash", label: "Dehy Has Flash", required: false },
    { id: "dehy_flash_eff", label: "Dehy Flash Eff", required: false },
    { id: "dehy_still_type", label: "Dehy Still Type", required: false },
    { id: "dehy_ch4_content", label: "Dehy CH4 Content", required: false },
    { id: "dehy_eff", label: "Dehy Eff", required: false },
    { id: "boiler_eff", label: "Boiler Efficiency (% or fraction)", required: false },
    { id: "trans_loss", label: "Transmission Loss (%)", required: false },
    { id: "heat_unit", label: "Heat Unit", required: false },
    { id: "carbon_content", label: "Carbon Content", required: false },
    { id: "fugitive_method", label: "Fugitive Method", required: false },
    { id: "fugitive_ppm", label: "Fugitive PPM", required: false },
    {
      id: "meter_uncertainty_pct",
      label: "Meter Uncertainty %",
      required: false,
    },
    { id: "gc_uncertainty_pct", label: "GC Uncertainty %", required: false },
    { id: "user_unc_co2", label: "User Unc CO2", required: false },
    { id: "user_unc_ch4", label: "User Unc CH4", required: false },
    { id: "user_unc_n2o", label: "User Unc N2O", required: false },
  ],
  activity_scope2: [
    { id: "facility_id", label: "Region", required: true },
    { id: "year", label: "Year", required: true },
    { id: "month", label: "Month", required: true },
    { id: "grid_region", label: "Grid Region", required: false, hint: "e.g. Algerian National Grid" },
    { id: "consumption", label: "Consumption", required: true },
    { id: "unit", label: "Unit", required: true, hint: "kWh, MWh, GWh (steam: MMBtu, GJ)" },
    { id: "source_type", label: "Source Type", required: false, hint: "electricity (default), indirect_steam, cogen_allocation" },
    { id: "factor", label: "Supplier Factor", required: false, hint: "kg CO2e/kWh, when the grid is not listed" },
  ],
  activity_scope3: [
    { id: "facility_id", label: "Region", required: true },
    { id: "year", label: "Year", required: true },
    { id: "month", label: "Month", required: true },
    { id: "category", label: "Category #", required: true, hint: "1-15" },
    {
      id: "sub_category",
      label: "Activity Type",
      required: true,
      hint: "e.g. Steel, Flight",
    },
    { id: "amount", label: "Quantity", required: true },
    { id: "unit", label: "Unit", required: true },
    { id: "emission_factor", label: "Emission Factor", required: false, hint: "kg CO2e per unit; if empty, the Scope 3 form factor of the activity is used" },
    { id: "ef_unit", label: "EF Unit", required: false, hint: "kg (default) or t CO2e per unit" },
    { id: "co2e", label: "Total CO2e (t)", required: false, hint: "Supplier-specific total instead of a factor" },
    { id: "notes", label: "Notes", required: false },
  ],
  custom_factors: [
    {
      id: "name",
      label: "Factor Name",
      required: true,
      hint: "e.g. Specialized Gas",
    },
    {
      id: "parent_fuel",
      label: "Parent API Fuel",
      required: false,
      hint: "e.g. Natural Gas",
    },
    { id: "unit", label: "Unit", required: true, hint: "e.g. scf, m3" },
    {
      id: "co2_factor",
      label: "CO2 Factor",
      required: true,
      hint: "Numeric value",
    },
    {
      id: "ch4_factor",
      label: "CH4 Factor",
      required: false,
      hint: "Numeric value",
    },
    {
      id: "n2o_factor",
      label: "N2O Factor",
      required: false,
      hint: "Numeric value",
    },
    {
      id: "co_factor",
      label: "CO Factor",
      required: false,
      hint: "Numeric value",
    },
    {
      id: "co2_uncertainty",
      label: "CO2 Uncertainty (%)",
      required: false,
      hint: "e.g. 5",
    },
    {
      id: "ch4_uncertainty",
      label: "CH4 Uncertainty (%)",
      required: false,
      hint: "e.g. 50",
    },
    {
      id: "n2o_uncertainty",
      label: "N2O Uncertainty (%)",
      required: false,
      hint: "e.g. 150",
    },
    { id: "usage", label: "Usage", required: false, hint: "e.g. combustion" },
  ],
  production: [
    { id: "facility_id", label: "Region", required: true },
    { id: "activity", label: "Activity", required: false },
    { id: "division", label: "Division", required: false },
    { id: "field", label: "Field", required: false },
    { id: "year", label: "Year", required: true },
    { id: "month", label: "Month", required: true },
    { id: "oil_amount", label: "Oil Quantity", required: false },
    { id: "oil_unit", label: "Oil Unit", required: false, hint: "bbl" },
    { id: "gas_amount", label: "Gas Quantity", required: false },
    { id: "gas_unit", label: "Gas Unit", required: false, hint: "mscf" },
  ],
  mitigation: [
    { id: "facility_id", label: "Region", required: true },
    { id: "name", label: "Project Name", required: true },
    {
      id: "project_type",
      label: "Type",
      required: false,
      hint: "e.g. CCUS, REC",
    },
    { id: "year", label: "Year", required: true },
    { id: "quantity_tco2e", label: "tCO2e Avoided", required: true },
    { id: "status", label: "Status", required: false, hint: "Active, Planned" },
    {
      id: "start_date",
      label: "Start Date",
      required: false,
      hint: "YYYY-MM-DD",
    },
    { id: "end_date", label: "End Date", required: false, hint: "YYYY-MM-DD" },
    { id: "investment_amount", label: "Investment", required: false },
    { id: "description", label: "Description", required: false },
  ],
  facilities: [
    { id: "name", label: "Region Name", required: true },
    { id: "region", label: "Region", required: false, hint: "Region the facility belongs to (dashboard filter)" },
    { id: "code", label: "Facility Code", required: false, hint: "Unique code" },
    { id: "equity_share_pct", label: "Equity Share (%)", required: false, hint: "0-100; default 100" },
    { id: "operator_status", label: "Operator Status", required: false, hint: "operated or non-operated" },
    { id: "activity", label: "Activity", required: false },
    { id: "division", label: "Division", required: false },
    { id: "field", label: "Field / Block", required: false },
    { id: "location", label: "Location (Wilaya)", required: false },
    { id: "boundary_type", label: "Consolidation Approach", required: false },
    { id: "boundary_detail", label: "Boundary Details", required: false },
    { id: "segment", label: "Supply Chain Segment", required: false },
    { id: "latitude", label: "Latitude", required: false },
    { id: "longitude", label: "Longitude", required: false },
  ],
};
