import { t } from "../../i18n";
// System fields each bulk-import type accepts: { id, label, required, hint }.
export interface TemplateField {
  id: string;
  label: string;
  required: boolean;
  hint?: string;
}

export const TEMPLATES: Record<string, TemplateField[]> = {
  sources: [
    {
      id: "activity",
      label: t("Activity"),
      required: false,
      hint: t("e.g. Exploration & Production"),
    },
    {
      id: "division",
      label: t("Division"),
      required: false,
      hint: t("e.g. Production, Association"),
    },
    {
      id: "facility_id",
      label: t("Region"),
      required: true,
      hint: t("e.g. Hassi Messaoud"),
    },
    { id: "field", label: t("Field"), required: false },
    { id: "name", label: t("Equipment Name"), required: true },
    { id: "equipment_id", label: t("Equipment ID"), required: false },
    {
      id: "type",
      label: t("Process Type"),
      required: false,
      hint: t("e.g. combustion, flaring"),
    },
    {
      id: "fuel_type",
      label: t("Fuel Type"),
      required: false,
      hint: t("e.g. Natural Gas"),
    },
    { id: "design_capacity", label: t("Design Capacity"), required: false },
    { id: "installation_date", label: t("Installation Date"), required: false, hint: "YYYY-MM-DD" },
    { id: "status", label: t("Status"), required: false, hint: t("Active / Inactive") },
  ],
  activity: [
    { id: "activity", label: t("Activity"), required: false },
    { id: "division", label: t("Division"), required: false },
    { id: "facility_id", label: t("Region"), required: true },
    { id: "facility_name", label: t("Region / Facility"), required: false },
    { id: "field", label: t("Field"), required: false },
    { id: "group", label: t("Emission Source (Group)"), required: false },
    { id: "equipment", label: t("Equipment Name"), required: false },
    { id: "equipment_id", label: t("Equipment ID"), required: false },
    { id: "year", label: t("Year"), required: false },
    { id: "month", label: t("Month"), required: false },
    { id: "date", label: t("Date"), required: true },
    { id: "process", label: t("Process Type"), required: true },
    { id: "process_type", label: t("Process Type (legacy)"), required: false },
    { id: "fuel", label: t("Activity / Fuel"), required: false, hint: t("Emission factor name (default and custom rows)") },
    { id: "fuel_type", label: t("Fuel Type (legacy)"), required: false },
    { id: "quantity", label: t("Quantity"), required: true },
    { id: "amount", label: t("Amount"), required: false },
    { id: "unit", label: t("Unit"), required: true },
    { id: "factor_type", label: t("Factor Type"), required: false },
    { id: "hhv", label: "HHV", required: false },
    { id: "ef_unit", label: t("EF Unit"), required: false },
    { id: "combustion_efficiency", label: t("Combustion Eff"), required: false },
    { id: "flare_type", label: t("Flare Type"), required: false },
    { id: "ch4_content", label: t("CH4 Content %"), required: false },
    { id: "co2_content", label: t("CO2 Content %"), required: false },
    { id: "control_efficiency", label: t("Control Eff"), required: false },
    { id: "operating_temperature", label: t("Op Temp"), required: false },
    { id: "temp_unit", label: t("Temp Unit"), required: false },
    { id: "operating_pressure", label: t("Op Press"), required: false },
    { id: "press_unit", label: t("Press Unit"), required: false },
    { id: "z_factor", label: t("Z Factor"), required: false },
    { id: "c1", label: "C1", required: false },
    { id: "c2", label: "C2", required: false },
    { id: "c3", label: "C3", required: false },
    { id: "c4", label: "C4", required: false },
    { id: "c5", label: "C5", required: false },
    { id: "c6", label: "C6", required: false },
    { id: "c7", label: "C7", required: false },
    { id: "c8", label: "C8", required: false },
    { id: "c9", label: "C9", required: false },
    { id: "c10", label: "C10+", required: false },
    { id: "co2_mol", label: t("CO2 Mol %"), required: false },
    { id: "n2_mol", label: t("N2 Mol %"), required: false },
    { id: "mud_type", label: t("Mud Type"), required: false },
    { id: "mud_unit", label: t("Mud Unit"), required: false },
    { id: "comp_method", label: t("Comp Method"), required: false },
    { id: "comp_rate", label: t("Comp Rate"), required: false },
    { id: "comp_duration", label: t("Comp Duration"), required: false },
    { id: "comp_flare_eff", label: t("Comp Flare Eff"), required: false },
    { id: "unload_depth", label: t("Unload Depth"), required: false },
    { id: "unload_diam", label: t("Unload Diam"), required: false },
    { id: "unload_press", label: t("Unload Press"), required: false },
    { id: "unload_freq", label: t("Unload Freq"), required: false },
    { id: "unload_flare_eff", label: t("Unload Flare Eff"), required: false },
    { id: "unload_temp", label: t("Unload Temp"), required: false },
    { id: "blowdown_pressure", label: t("BD Press"), required: false },
    { id: "blowdown_events", label: t("BD Events"), required: false },
    { id: "blowdown_temp", label: t("BD Temp"), required: false },
    { id: "blowdown_temp_unit", label: t("BD Temp Unit"), required: false },
    { id: "blowdown_press_unit", label: t("BD Press Unit"), required: false },
    { id: "tank_gor", label: t("Tank GOR"), required: false },
    { id: "tank_control_eff", label: t("Tank Control Eff"), required: false },
    { id: "tank_unit", label: t("Tank Unit"), required: false },
    { id: "tank_api_gravity", label: t("Tank API Gravity"), required: false },
    { id: "tank_throughput", label: t("Tank Throughput"), required: false },
    { id: "tank_throughput_unit", label: t("Tank Thr Unit"), required: false },
    { id: "tank_turnovers", label: t("Tank Turnovers"), required: false },
    { id: "pneu_type", label: t("Pneu Type"), required: false },
    { id: "pneu_count", label: t("Pneu Count"), required: false },
    { id: "pneu_bleed_rate", label: t("Pneu Bleed Rate"), required: false },
    { id: "pneu_hours", label: t("Pneu Hours"), required: false },
    { id: "pump_type", label: t("Pump Type"), required: false },
    { id: "pump_count", label: t("Pump Count"), required: false },
    { id: "pump_gas_rate", label: t("Pump Gas Rate"), required: false },
    { id: "pump_hours", label: t("Pump Hours"), required: false },
    { id: "comp_mode", label: t("Comp Mode"), required: false },
    { id: "comp_hours", label: t("Comp Hours"), required: false },
    { id: "comp_count", label: t("Comp Count"), required: false },
    { id: "operating_hours", label: t("Op Hours"), required: false },
    { id: "leak_count", label: t("Leak Count"), required: false },
    { id: "leak_duration", label: t("Leak Duration"), required: false },
    { id: "leak_rate", label: t("Leak Rate"), required: false },
    { id: "agr_throughput", label: t("AGR Throughput"), required: false },
    { id: "agr_co2_in", label: t("AGR CO2 In"), required: false },
    { id: "agr_co2_out", label: t("AGR CO2 Out"), required: false },
    { id: "agr_unit", label: t("AGR Unit"), required: false },
    { id: "agr_ch4_in", label: t("AGR CH4 In"), required: false },
    { id: "agr_ch4_slip", label: t("AGR CH4 Slip"), required: false },
    { id: "agr_control_eff", label: t("AGR Control Eff"), required: false },
    { id: "dehy_pump_rate", label: t("Dehy Pump Rate"), required: false },
    { id: "dehy_pump_unit", label: t("Dehy Pump Unit"), required: false },
    { id: "dehy_hours", label: t("Dehy Hours"), required: false },
    { id: "dehy_press", label: t("Dehy Press"), required: false },
    { id: "dehy_press_unit", label: t("Dehy Press Unit"), required: false },
    { id: "dehy_temp", label: t("Dehy Temp"), required: false },
    { id: "dehy_temp_unit", label: t("Dehy Temp Unit"), required: false },
    { id: "dehy_has_flash", label: t("Dehy Has Flash"), required: false },
    { id: "dehy_flash_eff", label: t("Dehy Flash Eff"), required: false },
    { id: "dehy_still_type", label: t("Dehy Still Type"), required: false },
    { id: "dehy_ch4_content", label: t("Dehy CH4 Content"), required: false },
    { id: "dehy_eff", label: t("Dehy Eff"), required: false },
    { id: "boiler_eff", label: t("Boiler Efficiency (% or fraction)"), required: false },
    { id: "trans_loss", label: t("Transmission Loss (%)"), required: false },
    { id: "heat_unit", label: t("Heat Unit"), required: false },
    { id: "carbon_content", label: t("Carbon Content"), required: false },
    { id: "fugitive_method", label: t("Fugitive Method"), required: false },
    { id: "fugitive_ppm", label: t("Fugitive PPM"), required: false },
    {
      id: "meter_uncertainty_pct",
      label: t("Meter Uncertainty %"),
      required: false,
    },
    { id: "gc_uncertainty_pct", label: t("GC Uncertainty %"), required: false },
    { id: "user_unc_co2", label: t("User Unc CO2"), required: false },
    { id: "user_unc_ch4", label: t("User Unc CH4"), required: false },
    { id: "user_unc_n2o", label: t("User Unc N2O"), required: false },
  ],
  activity_scope2: [
    { id: "facility_id", label: t("Region"), required: true },
    { id: "year", label: t("Year"), required: true },
    { id: "month", label: t("Month"), required: true },
    { id: "grid_region", label: t("Grid Region"), required: false, hint: t("e.g. Algerian National Grid") },
    { id: "consumption", label: t("Consumption"), required: true },
    { id: "unit", label: t("Unit"), required: true, hint: t("kWh, MWh, GWh (steam: MMBtu, GJ)") },
    { id: "source_type", label: t("Source Type"), required: false, hint: t("electricity (default), indirect_steam, cogen_allocation") },
    { id: "factor", label: t("Supplier Factor"), required: false, hint: t("kg CO2e/kWh, when the grid is not listed") },
  ],
  activity_scope3: [
    { id: "facility_id", label: t("Region"), required: true },
    { id: "year", label: t("Year"), required: true },
    { id: "month", label: t("Month"), required: true },
    { id: "category", label: t("Category #"), required: true, hint: "1-15" },
    {
      id: "sub_category",
      label: t("Activity Type"),
      required: true,
      hint: t("e.g. Steel, Flight"),
    },
    { id: "amount", label: t("Quantity"), required: true },
    { id: "unit", label: t("Unit"), required: true },
    { id: "emission_factor", label: t("Emission Factor"), required: false, hint: t("kg CO2e per unit; if empty, the Scope 3 form factor of the activity is used") },
    { id: "ef_unit", label: t("EF Unit"), required: false, hint: t("kg (default) or t CO2e per unit") },
    { id: "co2e", label: t("Total CO2e (t)"), required: false, hint: t("Supplier-specific total instead of a factor") },
    { id: "notes", label: t("Notes"), required: false },
  ],
  custom_factors: [
    {
      id: "name",
      label: t("Factor Name"),
      required: true,
      hint: t("e.g. Specialized Gas"),
    },
    {
      id: "parent_fuel",
      label: t("Parent API Fuel"),
      required: false,
      hint: t("e.g. Natural Gas"),
    },
    { id: "unit", label: t("Unit"), required: true, hint: t("e.g. scf, m3") },
    {
      id: "co2_factor",
      label: t("CO2 Factor"),
      required: true,
      hint: t("Numeric value"),
    },
    {
      id: "ch4_factor",
      label: t("CH4 Factor"),
      required: false,
      hint: t("Numeric value"),
    },
    {
      id: "n2o_factor",
      label: t("N2O Factor"),
      required: false,
      hint: t("Numeric value"),
    },
    {
      id: "co_factor",
      label: t("CO Factor"),
      required: false,
      hint: t("Numeric value"),
    },
    {
      id: "co2_uncertainty",
      label: t("CO2 Uncertainty (%)"),
      required: false,
      hint: "e.g. 5",
    },
    {
      id: "ch4_uncertainty",
      label: t("CH4 Uncertainty (%)"),
      required: false,
      hint: "e.g. 50",
    },
    {
      id: "n2o_uncertainty",
      label: t("N2O Uncertainty (%)"),
      required: false,
      hint: "e.g. 150",
    },
    { id: "usage", label: t("Usage"), required: false, hint: t("e.g. combustion") },
  ],
  production: [
    { id: "facility_id", label: t("Region"), required: true },
    { id: "activity", label: t("Activity"), required: false },
    { id: "division", label: t("Division"), required: false },
    { id: "field", label: t("Field"), required: false },
    { id: "year", label: t("Year"), required: true },
    { id: "month", label: t("Month"), required: true },
    { id: "oil_amount", label: t("Oil Quantity"), required: false },
    { id: "oil_unit", label: t("Oil Unit"), required: false, hint: t("bbl") },
    { id: "gas_amount", label: t("Gas Quantity"), required: false },
    { id: "gas_unit", label: t("Gas Unit"), required: false, hint: t("mscf") },
  ],
  mitigation: [
    { id: "facility_id", label: t("Region"), required: true },
    { id: "name", label: t("Project Name"), required: true },
    {
      id: "project_type",
      label: t("Type"),
      required: false,
      hint: t("e.g. CCUS, REC"),
    },
    { id: "year", label: t("Year"), required: true },
    { id: "quantity_tco2e", label: t("tCO2e Avoided"), required: true },
    { id: "status", label: t("Status"), required: false, hint: t("Active, Planned") },
    {
      id: "start_date",
      label: t("Start Date"),
      required: false,
      hint: "YYYY-MM-DD",
    },
    { id: "end_date", label: t("End Date"), required: false, hint: "YYYY-MM-DD" },
    { id: "investment_amount", label: t("Investment"), required: false },
    { id: "description", label: t("Description"), required: false },
  ],
  facilities: [
    { id: "name", label: t("Region Name"), required: true },
    { id: "region", label: t("Region"), required: false, hint: t("Region the facility belongs to (dashboard filter)") },
    { id: "code", label: t("Facility Code"), required: false, hint: t("Unique code") },
    { id: "equity_share_pct", label: t("Equity Share (%)"), required: false, hint: t("0-100; default 100") },
    { id: "operator_status", label: t("Operator Status"), required: false, hint: t("operated or non-operated") },
    { id: "activity", label: t("Activity"), required: false },
    { id: "division", label: t("Division"), required: false },
    { id: "field", label: t("Field / Block"), required: false },
    { id: "location", label: t("Location (Wilaya)"), required: false },
    { id: "boundary_type", label: t("Consolidation Approach"), required: false },
    { id: "boundary_detail", label: t("Boundary Details"), required: false },
    { id: "segment", label: t("Supply Chain Segment"), required: false },
    { id: "latitude", label: t("Latitude"), required: false },
    { id: "longitude", label: t("Longitude"), required: false },
  ],
};
