"""Add GHG uncertainties to CustomFactor

Revision ID: 2ef6f882b02c
Revises: 61bacaad00dc
Create Date: 2026-07-25 19:14:30.074251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef6f882b02c'
down_revision = '61bacaad00dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('co2_uncertainty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ch4_uncertainty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('n2o_uncertainty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope3_emissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scope3_emissions_status'))
        batch_op.drop_index(batch_op.f('ix_scope3_emissions_facility_id'))

    with op.batch_alter_table('scope2_emissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope2_emissions_status'))
        batch_op.create_index(batch_op.f('ix_scope2_dashboard'), ['status', 'year', 'facility_id', 'activity', 'division'], unique=False)
        batch_op.alter_column('field',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('division',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('activity',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('production_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prod_dashboard'), ['year', 'facility_id', 'activity', 'division'], unique=False)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('emissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emissions_dashboard'), ['status', 'year', 'facility_id', 'activity', 'division'], unique=False)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('emission_sources', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.drop_column('n2o_uncertainty')
        batch_op.drop_column('ch4_uncertainty')
        batch_op.drop_column('co2_uncertainty')

    op.create_table('_alembic_tmp_emission_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('facility_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('design_capacity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('installation_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('activity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('division', sa.VARCHAR(length=100), nullable=True),
    sa.Column('field', sa.VARCHAR(length=100), nullable=True),
    sa.Column('code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('equipment_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
