"""Add uncertainty_pct and qa_flag

Revision ID: 52c620a620d2
Revises: 7fe333372c71
Create Date: 2026-08-15 22:20:32.267979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c620a620d2'
down_revision = '7fe333372c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncertainty_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('emissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncertainty_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('qa_flag', sa.String(length=255), nullable=True))

    with op.batch_alter_table('scope2_emissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncertainty_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('qa_flag', sa.String(length=255), nullable=True))

    with op.batch_alter_table('scope3_emissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncertainty_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('qa_flag', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope3_emissions', schema=None) as batch_op:
        batch_op.drop_column('qa_flag')
        batch_op.drop_column('uncertainty_pct')

    with op.batch_alter_table('scope2_emissions', schema=None) as batch_op:
        batch_op.drop_column('qa_flag')
        batch_op.drop_column('uncertainty_pct')

    with op.batch_alter_table('emissions', schema=None) as batch_op:
        batch_op.drop_column('qa_flag')
        batch_op.drop_column('uncertainty_pct')

    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.drop_column('uncertainty_pct')

    # ### end Alembic commands ###
