"""Add uncertainty_pct and qa_flag

Revision ID: 52c620a620d2
Revises: 7fe333372c71
Create Date: 2026-08-15 22:20:32.267979

"""
from alembic import op
import sqlalchemy as sa


def _bind():
    return op.get_bind()


def _add(table, column):
    from schema_sync import has_column
    if has_table_(table) and not has_column(_bind(), table, column.name):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.add_column(column)


def has_table_(table):
    from schema_sync import has_table
    return has_table(_bind(), table)


# revision identifiers, used by Alembic.
revision = '52c620a620d2'
down_revision = '7fe333372c71'
branch_labels = None
depends_on = None


def upgrade():
    _add("custom_factors", sa.Column("uncertainty_pct", sa.Float(), nullable=True))
    for table in ("emissions", "scope2_emissions", "scope3_emissions"):
        _add(table, sa.Column("uncertainty_pct", sa.Float(), nullable=True))
        _add(table, sa.Column("qa_flag", sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope3_emissions', schema=None) as batch_op:
        batch_op.drop_column('qa_flag')
        batch_op.drop_column('uncertainty_pct')

    with op.batch_alter_table('scope2_emissions', schema=None) as batch_op:
        batch_op.drop_column('qa_flag')
        batch_op.drop_column('uncertainty_pct')

    with op.batch_alter_table('emissions', schema=None) as batch_op:
        batch_op.drop_column('qa_flag')
        batch_op.drop_column('uncertainty_pct')

    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.drop_column('uncertainty_pct')

    # ### end Alembic commands ###
