"""add performance indexes

Revision ID: 7fe333372c71
Revises: 2ef6f882b02c
Create Date: 2026-07-31 21:02:49.219724

"""

from alembic import op
import sqlalchemy as sa


def _bind():
    return op.get_bind()


def _add(table, column):
    from schema_sync import has_column
    if has_table_(table) and not has_column(_bind(), table, column.name):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.add_column(column)


def has_table_(table):
    from schema_sync import has_table
    return has_table(_bind(), table)


# revision identifiers, used by Alembic.
revision = "7fe333372c71"
down_revision = "2ef6f882b02c"
branch_labels = None
depends_on = None


def upgrade():
    # Idempotent. The original autogenerated TEXT -> String(100) alterations are
    # type-affinity no-ops on SQLite and were never required for correctness, so
    # only the index changes are applied, and only when missing.
    from schema_sync import has_index

    bind = _bind()
    if has_table_("_alembic_tmp_emission_sources"):
        op.drop_table("_alembic_tmp_emission_sources")
    indexes = {
        "emissions": [("ix_emissions_activity", ["activity"]), ("ix_emissions_division", ["division"])],
        "production_data": [
            ("ix_production_data_activity", ["activity"]),
            ("ix_production_data_division", ["division"]),
            ("ix_production_data_facility_id", ["facility_id"]),
            ("ix_production_data_year", ["year"]),
        ],
        "scope2_emissions": [
            ("ix_scope2_emissions_activity", ["activity"]),
            ("ix_scope2_emissions_division", ["division"]),
            ("ix_scope2_emissions_status", ["status"]),
        ],
        "scope3_emissions": [
            ("ix_scope3_emissions_facility_id", ["facility_id"]),
            ("ix_scope3_emissions_status", ["status"]),
        ],
    }
    for table, specs in indexes.items():
        if not has_table_(table):
            continue
        for name, cols in specs:
            if not has_index(bind, table, name):
                op.create_index(name, table, cols, unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scope3_emissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scope3_emissions_status"))
        batch_op.drop_index(batch_op.f("ix_scope3_emissions_facility_id"))

    with op.batch_alter_table("scope2_emissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scope2_emissions_status"))
        batch_op.drop_index(batch_op.f("ix_scope2_emissions_division"))
        batch_op.drop_index(batch_op.f("ix_scope2_emissions_activity"))
        batch_op.create_index(
            batch_op.f("ix_scope2_dashboard"),
            ["status", "year", "facility_id", "activity", "division"],
            unique=False,
        )
        batch_op.alter_column(
            "field",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "region",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "division",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "activity",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("production_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_production_data_year"))
        batch_op.drop_index(batch_op.f("ix_production_data_facility_id"))
        batch_op.drop_index(batch_op.f("ix_production_data_division"))
        batch_op.drop_index(batch_op.f("ix_production_data_activity"))
        batch_op.create_index(
            batch_op.f("ix_prod_dashboard"),
            ["year", "facility_id", "activity", "division"],
            unique=False,
        )
        batch_op.alter_column(
            "region",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("facilities", schema=None) as batch_op:
        batch_op.alter_column(
            "region",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("emissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_emissions_division"))
        batch_op.drop_index(batch_op.f("ix_emissions_activity"))
        batch_op.create_index(
            batch_op.f("ix_emissions_dashboard"),
            ["status", "year", "facility_id", "activity", "division"],
            unique=False,
        )
        batch_op.alter_column(
            "region",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("emission_sources", schema=None) as batch_op:
        batch_op.alter_column(
            "region",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    op.create_table(
        "_alembic_tmp_emission_sources",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("facility_id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=120), nullable=True),
        sa.Column("type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("fuel_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("design_capacity", sa.VARCHAR(length=50), nullable=True),
        sa.Column("installation_date", sa.VARCHAR(length=20), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("activity", sa.VARCHAR(length=100), nullable=True),
        sa.Column("division", sa.VARCHAR(length=100), nullable=True),
        sa.Column("field", sa.VARCHAR(length=100), nullable=True),
        sa.Column("code", sa.VARCHAR(length=50), nullable=True),
        sa.Column("external_id", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_by", sa.INTEGER(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("equipment_id", sa.VARCHAR(length=50), nullable=True),
        sa.Column("region", sa.VARCHAR(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###
