"""Add segment field to facilities table

Revision ID: 815d10c5bbe4
Revises: 
Create Date: 2026-02-11 20:38:18.633982

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "815d10c5bbe4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("facilities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("segment", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("facilities", schema=None) as batch_op:
        batch_op.drop_column("segment")

    # ### end Alembic commands ###
