"""Add segment field to facilities table

Revision ID: 815d10c5bbe4
Revises: 
Create Date: 2026-02-11 20:38:18.633982

"""

from alembic import op
import sqlalchemy as sa


def _bind():
    return op.get_bind()


def _add(table, column):
    from schema_sync import has_column
    if has_table_(table) and not has_column(_bind(), table, column.name):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.add_column(column)


def has_table_(table):
    from schema_sync import has_table
    return has_table(_bind(), table)


# revision identifiers, used by Alembic.
revision = "815d10c5bbe4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Idempotent: the column may already exist when the table was created by db.create_all().
    _add("facilities", sa.Column("segment", sa.String(length=20), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("facilities", schema=None) as batch_op:
        batch_op.drop_column("segment")

    # ### end Alembic commands ###
