"""sync_audit_hardening_and_foreign_keys

Revision ID: a6274c2ef1f5
Revises: b2d5f8e31a42
Create Date: 2026-10-06 16:15:24.998253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6274c2ef1f5'
down_revision = 'b2d5f8e31a42'
branch_labels = None
depends_on = None


def upgrade():
    from schema_sync import has_index
    bind = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cap_emissions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cap_emissions_updated_by_users', 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key('fk_cap_emissions_approved_by_users', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        if not has_index(bind, 'custom_factors', 'ix_custom_factors_status'):
            batch_op.create_index(batch_op.f('ix_custom_factors_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_custom_factors_approved_by_users', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('sbti_targets', schema=None) as batch_op:
        batch_op.alter_column('scope_coverage',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'S1S2S3'"))

    with op.batch_alter_table('scope2_emissions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_scope2_emissions_updated_by_users', 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('scope3_emissions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_scope3_emissions_updated_by_users', 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('scope3_emissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scope3_emissions_updated_by_users', type_='foreignkey')

    with op.batch_alter_table('scope2_emissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scope2_emissions_updated_by_users', type_='foreignkey')

    with op.batch_alter_table('sbti_targets', schema=None) as batch_op:
        batch_op.alter_column('scope_coverage',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'S1S2S3'"))

    with op.batch_alter_table('custom_factors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_custom_factors_approved_by_users', type_='foreignkey')
        if has_index(bind, 'custom_factors', 'ix_custom_factors_status'):
            batch_op.drop_index(batch_op.f('ix_custom_factors_status'))
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('cap_emissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cap_emissions_approved_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_cap_emissions_updated_by_users', type_='foreignkey')

    # ### end Alembic commands ###
