import sqlite3,sys
con=sqlite3.connect(sys.argv[1] if len(sys.argv)>1 else "C:/Users/samsung/Desktop/H2/audit/db/snapshot_original.db")
Q={
"fk_check": "pragma foreign_key_check",
"em orphan facility":"select count(*) from emissions e where facility_id is not null and facility_id not in (select id from facilities)",
"em null facility":"select count(*) from emissions where facility_id is null",
"s2 orphan":"select count(*) from scope2_emissions where facility_id not in (select id from facilities)",
"s3 orphan":"select count(*) from scope3_emissions where facility_id not in (select id from facilities)",
"s2 null fac":"select count(*) from scope2_emissions where facility_id is null",
"s3 null fac":"select count(*) from scope3_emissions where facility_id is null",
"prod orphan":"select count(*) from production_data where facility_id not in (select id from facilities)",
"approved_by orphan e":"select count(*) from emissions where approved_by is not null and approved_by not in (select id from users)",
"created_by orphan e":"select count(*) from emissions where created_by is not null and created_by not in (select id from users)",
"status dist e":"select status,count(*),sum(approved_by is null),sum(approved_at is null) from emissions group by status",
"status dist s2":"select status,count(*),sum(approved_by is null),sum(approved_at is null) from scope2_emissions group by status",
"status dist s3":"select status,count(*),sum(approved_by is null),sum(approved_at is null) from scope3_emissions group by status",
"co2e null e":"select count(*) from emissions where co2e_total is null",
"co2e negative e":"select count(*) from emissions where co2e_total<0",
"gwp versions":"select gwp_version,count(*) from emissions group by 1",
"co2e mismatch AR5 (co2+28ch4+265n2o)": "select count(*) from emissions where abs(co2e_total - (coalesce(co2_emissions,0)+28*coalesce(ch4_emissions,0)+265*coalesce(n2o_emissions,0))) > 1e-6*max(1,abs(co2e_total))",
"dup prod fac/yr/mo":"select count(*) from (select facility_id,year,month,count(*) c from production_data group by 1,2,3 having c>1)",
"dup emissions (fac,yr,mo,proc,fuel,qty,unit)":"select count(*),sum(c) from (select count(*) c from emissions group by facility_id,year,month,process_type,fuel_type,quantity,unit,equipment_id having c>1)",
"dup s2":"select count(*),sum(c) from (select count(*) c from scope2_emissions group by facility_id,year,month,source_type,electricity_kwh,steam_ton,heat_mmbtu having c>1)",
"dup s3":"select count(*),sum(c) from (select count(*) c from scope3_emissions group by facility_id,year,month,category,activity_data,unit having c>1)",
"month out of range e":"select count(*) from emissions where month is not null and (month<1 or month>12)",
"month out of range prod":"select count(*) from production_data where month<1 or month>12",
"year odd e":"select min(year),max(year) from emissions",
"null record_id":"select count(*) from emissions where record_id is null",
"facility dup name":"select count(*) from (select name,count(*) c from facilities group by name having c>1)",
"fac equity out of range":"select count(*) from facilities where equity_share_pct<0 or equity_share_pct>100",
"s2 co2e null":"select count(*) from scope2_emissions where co2e is null",
"typeof co2e":"select typeof(co2e_total),count(*) from emissions group by 1",
"typeof year":"select typeof(year),count(*) from emissions group by 1",
"typeof qty":"select typeof(quantity),count(*) from emissions group by 1",
"em activity/division mismatch facility":"select count(*) from emissions e join facilities f on f.id=e.facility_id where coalesce(e.activity,'')<>coalesce(f.activity,'') or coalesce(e.division,'')<>coalesce(f.division,'')",
"cf orphan created_by":"select count(*) from custom_factors where created_by not in (select id from users)",
"activity_log users orphan":"select count(*) from activity_log where user_id is not null and user_id not in (select id from users)",
"notif orphan":"select count(*) from notifications where user_id is not null and user_id not in (select id from users)",
"ogmp orphan":"select count(*) from ogmp_surveys where facility_id not in (select id from facilities)",
"cap orphan":"select count(*) from cap_emissions where facility_id not in (select id from facilities)",
"flare orphan":"select count(*) from flaring_details where facility_id not in (select id from facilities)",
"equity orphan":"select count(*) from facility_equity_shares where facility_id not in (select id from facilities)",
"level log orphan":"select count(*) from level_upgrade_logs where facility_id not in (select id from facilities)",
"src orphan":"select count(*) from emission_sources where facility_id is not null and facility_id not in (select id from facilities)",
"custom factor refs in emissions (factor_source=custom)":"select count(*) from emissions where factor_source='custom'",
"approved but status not Verified":"select status,count(*) from emissions where approved_by is not null group by status",
}
for k,q in Q.items():
    try: print(k, "=>", con.execute(q).fetchall()[:15])
    except Exception as e: print(k,"ERR",e)
