import { start, OUT, UI } from "./lib.mjs";
const PRESS = process.argv[2] || "200";
const { browser, page, log } = await start("admin");
await page.goto(UI + "/emissions?scope=scope1"); await page.waitForTimeout(9000);
await page.locator(".dropdown-selected", { hasText: "Select Region" }).click(); await page.waitForTimeout(500);
await page.locator(".dropdown-option").nth(1).click(); await page.waitForTimeout(800);
await page.locator(".dropdown-selected", { hasText: "Stationary Combustion" }).click(); await page.waitForTimeout(500);
await page.locator(".dropdown-option", { hasText: "Dehydrator" }).first().click(); await page.waitForTimeout(1000);
const grp = (t) => page.locator(".input-group").filter({ has: page.locator("label", { hasText: t }) }).last();
await grp("Gas Throughput").locator("input").fill("1000");
await grp("Pump").locator("input").first().fill("5");
await grp("Gas CH4 Content").locator("input").fill("85");
await grp("Operating Hours").locator("input").fill("8760");
await grp("Contactor Pressure").locator("input").fill(PRESS);
await grp("Contactor Temperature").locator("input").fill("100");
console.log("throughput label:", await grp("Gas Throughput").locator("label").innerText());
log.reqs.length = 0;
await page.getByText("Calculate & Submit", { exact: false }).click(); await page.waitForTimeout(3000);
const post = log.reqs.find(r => r.m === "POST" && r.u.startsWith("/api/emissions"));
const resp = log.resps.find(r => r.u.startsWith("/api/emissions") && r.body && r.body.includes("totalCo2e"));
if (post) { const b = JSON.parse(post.body); console.log("amount/unit:", b.amount, b.unit, "| calc_inputs:", JSON.stringify(b.calc_inputs)); }
else console.log("toasts:", await page.locator("[class*=toast]").allInnerTexts());
console.log("RESP:", resp && resp.body.slice(0, 200));
await browser.close();
