import { start, OUT, UI } from "./lib.mjs";
const { browser, page, log } = await start("admin");
await page.route("**/api/data/production**", r => r.request().method() === "GET" ? r.fulfill({ status: 500, contentType: "application/json", body: '{"error":"boom"}' }) : r.continue());
await page.route("**/api/custom-factors**", r => r.fulfill({ status: 500, contentType: "application/json", body: '{"error":"boom"}' }));
await page.goto(UI + "/manage-data"); await page.waitForTimeout(8000);
await page.locator(".manage-nav-item", { hasText: /Production/ }).click(); await page.waitForTimeout(2000);
const t1 = await page.locator("[class*=toast]").allInnerTexts();
const body1 = (await page.locator("body").innerText()).replace(/s+/g, " "); const i = body1.indexOf("Save Record");
console.log("MANAGE production toasts:", JSON.stringify(t1)); console.log("content after form:", body1.slice(i, i + 400));
await page.screenshot({ path: OUT + "err_md.png" });
await page.goto(UI + "/reference-data"); await page.waitForTimeout(6000);
const t2 = await page.locator("[class*=toast]").allInnerTexts();
const body2 = (await page.locator("body").innerText()).replace(/s+/g, " "); const j2 = body2.indexOf("Custom & Regional Factors");
console.log("REFDATA toasts:", JSON.stringify(t2)); console.log("custom section:", body2.slice(j2, j2 + 300));
await page.screenshot({ path: OUT + "err_ref.png" });
console.log("pageerrors:", log.errors.filter(e => e.startsWith("PAGEERROR")));
await browser.close();
