import { start, OUT, UI } from "./lib.mjs";
const { browser, page, log } = await start("admin");
await page.goto(UI + "/emissions?scope=scope1"); await page.waitForTimeout(9000);
const ids = async () => (await page.locator("table tbody tr").allInnerTexts()).map(t => t.replace(/\s+/g, " ").slice(0, 60));
const p1 = await ids();
log.reqs.length = 0;
await page.getByRole("button", { name: "Next" }).click(); await page.waitForTimeout(2500);
const p2 = await ids();
console.log("req:", log.reqs.filter(r => r.u.includes("/emissions?")).map(r => r.u));
const resp = log.resps.filter(r => r.u.includes("/emissions?")).pop(); const j = JSON.parse(resp.body);
console.log("resp current_page", j.current_page, "first id", (j.emissions||j.data)[0].id);
console.log("pager:", await page.getByText(/Page \d+ of/).allInnerTexts(), "same rows:", JSON.stringify(p1) === JSON.stringify(p2));
console.log(p1[0]); console.log(p2[0]);
await browser.close();
