import { start, OUT, UI } from "./lib.mjs";
const { browser, page, log } = await start("admin");
await page.goto(UI + "/reports"); await page.waitForTimeout(4000);
const sels = await page.$$eval("select", ss => ss.map(s => ({ v: s.value, shown: s.options[s.selectedIndex]?.text, opts: [...s.options].map(o => o.value).slice(0, 12) })));
console.log(JSON.stringify(sels, null, 0));
log.reqs.length = 0;
await page.getByText("2025 Master Report (PDF)").click(); await page.waitForTimeout(3000);
console.log(log.reqs.map(r => r.m + " " + r.u));
console.log(log.resps.filter(r=>r.u.includes("master")).map(r => r.s + " " + r.u));
await page.screenshot({ path: OUT + "reports.png" });
await browser.close();
