"""
API GHG Compendium 2021 - Chapter 7: Equipment Leaks / Fugitive Emissions
Authoritative Reference Factor Database for ONSHORE OIL & GAS OPERATIONS ONLY

Covered API Sections & Tables:
- §7.2.2 Table 7-1: Gas Production Facility-Level Factors
- §7.2.2 Table 7-2: Crude Oil Production Facility-Level Factors
- §7.2.2 Table 7-9: Equipment-Level Factors for Crude Oil Production (Heavy & Light)
- §7.2.2 Table 7-10: Equipment-Level Factors for Natural Gas Production
- §7.2.2 Table 7-11: Component-Level Average Factors (EPA 1995 / API) by Service (Gas, Light Oil, Heavy Oil, Water/Oil)
- §7.2.2 Table 7-15 & 7-16: Method 21 Screening Ranges (<10,000 ppmv Non-pegged vs >=10,000 ppmv Pegged)
- §7.2.2 Table 7-17 & 7-18: Method 21 Correlation Equations (a * PPM^b & Pegged Defaults)
- §7.2.2 Table 7-19, 7-20 & Subpart W Table W-1E: Optical Gas Imaging (OGI) Leaker Emission Factors
- §7.2.3 Table 7-29: Gathering & Boosting Equipment-Level Average Factors
- §7.2.3 Table 7-30: Gathering & Boosting Component-Level Average Factors

Metadata Schema:
factor_id, API_version, API_section, API_table, source_category, facility_type,
equipment_type, component_type, service_type, pollutant, factor_value, factor_unit,
time_basis, geographic_scope, methodology, source_reference
"""

API_CHAPTER7_ONSHORE_FACTORS = {
    # =========================================================================
    # TIER 1: FACILITY-LEVEL AVERAGE FACTORS (§7.2.2, Table 7-1 & Table 7-2)
    # =========================================================================
    "Facility - Gas Well Pad / Battery (Without Dehydrator)": {
        "factor_id": "API2021_CH7_TAB7_1_GAS_PAD_NODEY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-1",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 0.0543,
        "factor_unit": "tonne CH4/facility/day",
        "time_basis": "daily",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-1",
        "ch4": 0.0543,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/facility/day",
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Onshore natural gas well pad/battery without gas dehydrator average fugitive emissions",
    },
    "Facility - Gas Well Pad / Battery (With Dehydrator)": {
        "factor_id": "API2021_CH7_TAB7_1_GAS_PAD_DEHY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-1",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 0.106,
        "factor_unit": "tonne CH4/facility/day",
        "time_basis": "daily",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-1",
        "ch4": 0.106,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/facility/day",
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Onshore natural gas well pad/battery with gas dehydrator average fugitive emissions",
    },
    "Facility - Central Gas Production Facility": {
        "factor_id": "API2021_CH7_TAB7_1_CENTRAL_GAS_FAC",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-1",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 0.445,
        "factor_unit": "tonne CH4/facility/day",
        "time_basis": "daily",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-1",
        "ch4": 0.445,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/facility/day",
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Central gas processing/production facility average fugitive emissions",
    },
    "Facility - Oil Well Pad / Battery (Heavy Crude)": {
        "factor_id": "API2021_CH7_TAB7_2_OIL_PAD_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-2",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 0.0031,
        "factor_unit": "tonne CH4/facility/day",
        "time_basis": "daily",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-2",
        "ch4": 0.0031,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/facility/day",
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Onshore heavy crude oil well pad/battery (<20° API) average fugitive emissions",
    },
    "Facility - Oil Well Pad / Battery (Light Crude)": {
        "factor_id": "API2021_CH7_TAB7_2_OIL_PAD_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-2",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 0.0384,
        "factor_unit": "tonne CH4/facility/day",
        "time_basis": "daily",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-2",
        "ch4": 0.0384,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/facility/day",
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Onshore light crude oil well pad/battery (≥20° API) average fugitive emissions",
    },
    "Facility - Central Oil Treatment / Battery": {
        "factor_id": "API2021_CH7_TAB7_2_CENTRAL_OIL_BATTERY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-2",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 0.175,
        "factor_unit": "tonne CH4/facility/day",
        "time_basis": "daily",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-2",
        "ch4": 0.175,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/facility/day",
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Central oil treatment plant/tank battery average fugitive emissions",
    },

    # =========================================================================
    # TIER 2A: EQUIPMENT-LEVEL FACTORS - ONSHORE OIL PRODUCTION (§7.2.2, Table 7-9)
    # =========================================================================
    "Wellhead - Oil (Heavy Crude)": {
        "factor_id": "API2021_CH7_TAB7_9_WELL_OIL_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Wellhead",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 6.63e-07,
        "factor_unit": "tonne CH4/well/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "WellOilHeavy",
        "type": "equipment",
        "ch4": 6.63e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/well/hr",
        "segment": "Upstream",
        "process_category": "wellhead_fugitive",
        "description": "Oil wellhead fugitive emissions - heavy crude (API < 20°)",
    },
    "Wellhead - Oil (Light Crude)": {
        "factor_id": "API2021_CH7_TAB7_9_WELL_OIL_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Wellhead",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 1.56e-05,
        "factor_unit": "tonne CH4/well/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "WellOilLight",
        "type": "equipment",
        "ch4": 1.56e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/well/hr",
        "segment": "Upstream",
        "process_category": "wellhead_fugitive",
        "description": "Oil wellhead fugitive emissions - light crude (API ≥ 20°)",
    },
    "Separator - Heavy Crude": {
        "factor_id": "API2021_CH7_TAB7_9_SEP_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Separator",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 6.79e-07,
        "factor_unit": "tonne CH4/separator/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "SepHeavy",
        "type": "equipment",
        "ch4": 6.79e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/separator/hr",
        "segment": "Upstream",
        "process_category": "separator_fugitive",
        "description": "Separator fugitive emissions - heavy crude (<20° API)",
    },
    "Separator - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_SEP_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Separator",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 4.10e-05,
        "factor_unit": "tonne CH4/separator/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "SepLight",
        "type": "equipment",
        "ch4": 4.10e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/separator/hr",
        "segment": "Upstream",
        "process_category": "separator_fugitive",
        "description": "Separator fugitive emissions - light crude (≥20° API)",
    },
    "Heater-Treater - Heavy Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEATER_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Heater-Treater",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 3.18e-07,
        "factor_unit": "tonne CH4/heater/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaterHeavy",
        "type": "equipment",
        "ch4": 3.18e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/heater/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Heater-treater fugitive emissions - heavy crude (<20° API)",
    },
    "Heater-Treater - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEATER_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Heater-Treater",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 2.27e-05,
        "factor_unit": "tonne CH4/heater/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaterLight",
        "type": "equipment",
        "ch4": 2.27e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/heater/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Heater-treater fugitive emissions - light crude (≥20° API)",
    },
    "Header - Heavy Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEADER_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Header",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 1.36e-07,
        "factor_unit": "tonne CH4/header/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaderHeavy",
        "type": "equipment",
        "ch4": 1.36e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/header/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Production manifold/header fugitive emissions - heavy crude",
    },
    "Header - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEADER_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Header",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 1.41e-05,
        "factor_unit": "tonne CH4/header/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaderLight",
        "type": "equipment",
        "ch4": 1.41e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/header/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Production manifold/header fugitive emissions - light crude",
    },
    "Storage Tank Fugitive - Heavy Crude": {
        "factor_id": "API2021_CH7_TAB7_9_TANK_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Storage Tank",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 1.02e-07,
        "factor_unit": "tonne CH4/tank/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "TankFugHeavy",
        "type": "equipment",
        "ch4": 1.02e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/tank/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Atmospheric crude tank fitting/roof fugitive leaks - heavy crude",
    },
    "Storage Tank Fugitive - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_TANK_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Storage Tank",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 4.99e-06,
        "factor_unit": "tonne CH4/tank/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "TankFugLight",
        "type": "equipment",
        "ch4": 4.99e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/tank/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Atmospheric crude tank fitting/roof fugitive leaks - light crude",
    },
    "Compressor - Small Reciprocating": {
        "factor_id": "API2021_CH7_TAB7_9_COMP_SMALL_RECIP",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 3.69e-05,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "CompSmall",
        "type": "equipment",
        "ch4": 3.69e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 1.00, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Small reciprocating compressor fugitive emissions (light crude production)",
    },
    "Compressor - Large Reciprocating": {
        "factor_id": "API2021_CH7_TAB7_9_COMP_LARGE_RECIP",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 1.31e-02,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "CompLarge",
        "type": "equipment",
        "ch4": 1.31e-02,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 1.00, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Large reciprocating compressor fugitive emissions (light crude production)",
    },

    # =========================================================================
    # TIER 2A: EQUIPMENT-LEVEL FACTORS - ONSHORE GAS PRODUCTION (§7.2.2, Table 7-10)
    # =========================================================================
    "Wellhead - Gas": {
        "factor_id": "API2021_CH7_TAB7_10_WELL_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Wellhead",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.80e-05,
        "factor_unit": "tonne CH4/well/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "WellGas",
        "type": "equipment",
        "ch4": 1.80e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.257, "n2o": 0.0},
        "unit": "tonne CH4/well/hr",
        "segment": "Upstream",
        "process_category": "wellhead_fugitive",
        "description": "Natural gas wellhead fugitive emissions",
    },
    "Separator - Gas Production": {
        "factor_id": "API2021_CH7_TAB7_10_SEP_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Separator",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 4.42e-05,
        "factor_unit": "tonne CH4/separator/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "SepGas",
        "type": "equipment",
        "ch4": 4.42e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.879, "n2o": 0.0},
        "unit": "tonne CH4/separator/hr",
        "segment": "Upstream",
        "process_category": "separator_fugitive",
        "description": "Separator fugitive emissions in natural gas production",
    },
    "Heater - Gas Production": {
        "factor_id": "API2021_CH7_TAB7_10_HEATER_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Heater",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 2.75e-05,
        "factor_unit": "tonne CH4/heater/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "HeaterGas",
        "type": "equipment",
        "ch4": 2.75e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.60, "n2o": 0.0},
        "unit": "tonne CH4/heater/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Inline heater/bath heater fugitive emissions in gas production",
    },
    "Gas Dehydrator Unit - Fugitive Leaks": {
        "factor_id": "API2021_CH7_TAB7_10_DEHY_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Dehydrator",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 2.31e-05,
        "factor_unit": "tonne CH4/unit/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "DehyFugGas",
        "type": "equipment",
        "ch4": 2.31e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "unit": "tonne CH4/unit/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Piping and component fugitive leaks on gas dehydration units",
    },
    "Meter / Piping Run - Gas Production": {
        "factor_id": "API2021_CH7_TAB7_10_METER_RUN_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Meter Run",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.70e-05,
        "factor_unit": "tonne CH4/run/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "MeterRunGas",
        "type": "equipment",
        "ch4": 1.70e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.70, "n2o": 0.0},
        "unit": "tonne CH4/run/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Sales/allocation meter runs and associated valves/piping in gas production",
    },
    "Compressor - Gas Production Small Recip": {
        "factor_id": "API2021_CH7_TAB7_10_COMP_GAS_SMALL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 2.12e-04,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "CompGasSmall",
        "type": "equipment",
        "ch4": 2.12e-04,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 1.27, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Small reciprocating gas compressor in gas production",
    },
    "Compressor - Gas Production Large Recip": {
        "factor_id": "API2021_CH7_TAB7_10_COMP_GAS_LARGE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.22e-02,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "CompGasLarge",
        "type": "equipment",
        "ch4": 1.22e-02,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 2.02, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Large reciprocating gas compressor in gas production",
    },

    # =========================================================================
    # TIER 2B: COMPONENT-LEVEL AVERAGE FACTORS (§7.2.2, Table 7-11)
    # EPA 1995 Protocol Onshore Production Factors (kg TOC/hr/component)
    # =========================================================================
    "Component - Valve (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.0045,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0045 * 0.85 / 1000.0,  # default nominal tonne CH4/hr with 85% CH4
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0045,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in gas/vapor service (EPA 1995 Protocol Table 2-4)",
    },
    "Component - Valve (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.0025,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0025 * 0.60 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0025,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in light oil service (API ≥ 20°)",
    },
    "Component - Valve (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.0000084,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0000084 * 0.15 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0000084,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in heavy oil service (API < 20°)",
    },
    "Component - Valve (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.000098,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.000098 * 0.10 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.000098,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in water/oil emulsion service (>50% water)",
    },
    "Component - Pump Seal (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PUMP_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Pumps",
        "component_type": "Pump Seal",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.013,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.013 * 0.60 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.013,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.35, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pump seals in light oil service",
    },
    "Component - Pump Seal (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PUMP_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Pumps",
        "component_type": "Pump Seal",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.000032,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.000032 * 0.15 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.000032,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pump seals in heavy oil service",
    },
    "Component - Pump Seal (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PUMP_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Pumps",
        "component_type": "Pump Seal",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.000024,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.000024 * 0.10 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.000024,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pump seals in water/oil emulsion service",
    },
    "Component - Connector (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.00020,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00020 * 0.85 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00020,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Threaded / compression connectors in gas service",
    },
    "Component - Connector (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.00021,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00021 * 0.60 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00021,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Connectors in light oil service",
    },
    "Component - Connector (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.0000075,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0000075 * 0.15 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0000075,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Connectors in heavy oil service",
    },
    "Component - Connector (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.00011,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00011 * 0.10 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00011,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Connectors in water/oil service",
    },
    "Component - Flange (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.00039,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00039 * 0.85 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00039,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in gas service",
    },
    "Component - Flange (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.00011,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00011 * 0.60 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00011,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in light oil service",
    },
    "Component - Flange (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.00000039,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00000039 * 0.15 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00000039,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in heavy oil service",
    },
    "Component - Flange (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.0000029,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0000029 * 0.10 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0000029,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in water/oil service",
    },
    "Component - Open-Ended Line (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.0020,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0020 * 0.85 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0020,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in gas service",
    },
    "Component - Open-Ended Line (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.0014,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0014 * 0.60 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0014,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in light oil service",
    },
    "Component - Open-Ended Line (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.00014,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00014 * 0.15 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00014,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in heavy oil service",
    },
    "Component - Open-Ended Line (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.00025,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00025 * 0.10 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00025,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in water/oil service",
    },
    "Component - Other / PRV (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.0088,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0088 * 0.85 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0088,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in gas service",
    },
    "Component - Other / PRV (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.0075,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.0075 * 0.60 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0075,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in light oil service",
    },
    "Component - Other / PRV (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.000032,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.000032 * 0.15 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.000032,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in heavy oil service",
    },
    "Component - Other / PRV (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-11",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.00014,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-11 / EPA 1995 Protocol",
        "ch4": 0.00014 * 0.10 / 1000.0,
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00014,
        "unit": "kg TOC/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in water/oil service",
    },

    # =========================================================================
    # TIER 2: GATHERING & BOOSTING EQUIPMENT & COMPONENT FACTORS (§7.2.3, Tab 7-29, 7-30)
    # =========================================================================
    "Gathering - Compressor": {
        "factor_id": "API2021_CH7_TAB7_29_GATH_COMP",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-29",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.84e-03,
        "factor_unit": "tonne CH4/unit/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-29",
        "code": "GathComp",
        "type": "equipment",
        "ch4": 1.84e-03,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.14, "n2o": 0.0},
        "unit": "tonne CH4/unit/hr",
        "segment": "Midstream",
        "process_category": "gathering_boosting",
        "description": "Gathering compressor fugitive emissions",
    },
    "Gathering - Pipeline": {
        "factor_id": "API2021_CH7_TAB7_29_GATH_PIPE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-29",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Pipeline",
        "component_type": "Pipeline Segment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 4.50e-05,
        "factor_unit": "tonne CH4/km/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-29",
        "code": "GathPipe",
        "type": "equipment",
        "ch4": 4.50e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.35, "n2o": 0.0},
        "unit": "tonne CH4/km/hr",
        "segment": "Midstream",
        "process_category": "gathering_boosting",
        "description": "Gathering pipeline fugitive emissions",
    },
    "Component - Block Valve (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_BLOCK_VALVE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Block Valve",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 4.36e-06,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "BlockValve",
        "type": "component",
        "ch4": 4.36e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Block valve fugitive emissions in gathering & boosting",
    },
    "Component - Control Valve (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_CONTROL_VALVE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Control Valve",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.11e-05,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "ControlValve",
        "type": "component",
        "ch4": 1.11e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Control valve fugitive emissions in gathering & boosting",
    },
    "Component - Connector (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_CONN_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Connector",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 9.79e-07,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "ConnNonComp",
        "type": "component",
        "ch4": 9.79e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Connector fugitive emissions in gathering & boosting",
    },
    "Component - Flange (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_FLANGE_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Flange",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.05e-06,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "FlangeGath",
        "type": "component",
        "ch4": 1.05e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Flange fugitive emissions in gathering & boosting",
    },
    "Component - Pressure Relief Valve (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_PRV_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Pressure Relief Valve",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.39e-07,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "PRV",
        "type": "component",
        "ch4": 1.39e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valve fugitive emissions in gathering & boosting",
    },
    "Component - Pressure Regulator (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_REGULATOR_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Pressure Regulator",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.87e-06,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "Regulator",
        "type": "component",
        "ch4": 1.87e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Pressure regulator fugitive emissions in gathering & boosting",
    },
    "Component - Compressor Seal (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_COMP_SEAL_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Compressor Seal",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.54e-04,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "CompSeal",
        "type": "component",
        "ch4": 1.54e-04,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Compressor seal fugitive emissions in gathering & boosting",
    },
    "Component - Open-Ended Line (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_OEL_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Open-Ended Line",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.20e-05,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "OELGath",
        "type": "component",
        "ch4": 1.20e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in gathering & boosting",
    },
}

# =============================================================================
# TIER 3A: METHOD 21 SCREENING RANGES FACTORS (§7.2.2, Table 7-15 & Table 7-16)
# Expressed in kg TOC/hr/component
# Non-pegged (<10,000 ppmv) and Pegged (>=10,000 ppmv)
# =============================================================================
METHOD21_SCREENING_RANGES = {
    "valve_gas": {
        "component_type": "Valve",
        "service_type": "Gas",
        "non_pegged_ef": 0.000055,  # kg TOC/hr
        "pegged_10k_ef": 0.045,     # kg TOC/hr
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "valve_light_oil": {
        "component_type": "Valve",
        "service_type": "Light Oil",
        "non_pegged_ef": 0.000049,
        "pegged_10k_ef": 0.030,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "valve_heavy_oil": {
        "component_type": "Valve",
        "service_type": "Heavy Oil",
        "non_pegged_ef": 0.0000084,
        "pegged_10k_ef": 0.030,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "pump_light_oil": {
        "component_type": "Pump Seal",
        "service_type": "Light Oil",
        "non_pegged_ef": 0.00054,
        "pegged_10k_ef": 0.098,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "connector_gas": {
        "component_type": "Connector",
        "service_type": "Gas",
        "non_pegged_ef": 0.0000075,
        "pegged_10k_ef": 0.017,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "flange_gas": {
        "component_type": "Flange",
        "service_type": "Gas",
        "non_pegged_ef": 0.0000031,
        "pegged_10k_ef": 0.085,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "open_ended_line_gas": {
        "component_type": "Open-Ended Line",
        "service_type": "Gas",
        "non_pegged_ef": 0.00015,
        "pegged_10k_ef": 0.030,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
    "prv_gas": {
        "component_type": "Pressure Relief Valve",
        "service_type": "Gas",
        "non_pegged_ef": 0.000051,
        "pegged_10k_ef": 0.073,
        "unit": "kg TOC/hr/source",
        "table": "Table 7-15",
    },
}

# =============================================================================
# TIER 3C: OPTICAL GAS IMAGING (OGI) LEAKER FACTORS (§7.2.2, Table 7-19 / W-1E)
# Expressed in kg CH4/hr/component
# Leaker EF (detected leaking) vs Non-Leaker EF (surveyed non-leaking)
# =============================================================================
OGI_LEAKER_FACTORS = {
    "valve_gas": {
        "component_type": "Valve",
        "service_type": "Gas",
        "leaker_ef": 0.141,       # kg CH4/hr/leaker
        "non_leaker_ef": 0.00032,  # kg CH4/hr/non-leaker
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
    "valve_light_oil": {
        "component_type": "Valve",
        "service_type": "Light Oil",
        "leaker_ef": 0.096,
        "non_leaker_ef": 0.00015,
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
    "connector_gas": {
        "component_type": "Connector",
        "service_type": "Gas",
        "leaker_ef": 0.046,
        "non_leaker_ef": 0.000062,
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
    "flange_gas": {
        "component_type": "Flange",
        "service_type": "Gas",
        "leaker_ef": 0.085,
        "non_leaker_ef": 0.000080,
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
    "pump_light_oil": {
        "component_type": "Pump Seal",
        "service_type": "Light Oil",
        "leaker_ef": 0.210,
        "non_leaker_ef": 0.0011,
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
    "prv_gas": {
        "component_type": "Pressure Relief Valve",
        "service_type": "Gas",
        "leaker_ef": 0.245,
        "non_leaker_ef": 0.00021,
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
    "open_ended_line_gas": {
        "component_type": "Open-Ended Line",
        "service_type": "Gas",
        "leaker_ef": 0.052,
        "non_leaker_ef": 0.00014,
        "unit": "kg CH4/hr/source",
        "table": "Table 7-19 / EPA Subpart W Table W-1E",
    },
}

# Default stream compositions by service classification (API Compendium 2021)
DEFAULT_SERVICE_COMPOSITIONS = {
    "Gas": {"ch4_mol": 0.85, "co2_mol": 0.01, "nmhc_mol": 0.14, "mw": 18.5, "ch4_wt_in_toc": 0.85},
    "Light Oil": {"ch4_mol": 0.60, "co2_mol": 0.005, "nmhc_mol": 0.395, "mw": 24.0, "ch4_wt_in_toc": 0.60},
    "Heavy Oil": {"ch4_mol": 0.15, "co2_mol": 0.002, "nmhc_mol": 0.848, "mw": 32.0, "ch4_wt_in_toc": 0.15},
    "Water/Oil": {"ch4_mol": 0.10, "co2_mol": 0.001, "nmhc_mol": 0.899, "mw": 28.0, "ch4_wt_in_toc": 0.10},
}
