"""
API GHG Compendium 2021 - Chapter 7: Equipment Leaks / Fugitive Emissions
Authoritative Reference Factor Database for ONSHORE OIL & GAS OPERATIONS ONLY

Covered API Sections & Tables:
- §7.2.2 Table 7-1: Gas Production Facility-Level Factors
- §7.2.2 Table 7-2: Crude Oil Production Facility-Level Factors
- §7.2.2 Table 7-9: Equipment-Level Factors for Crude Oil Production (Heavy & Light)
- §7.2.2 Table 7-10: Equipment-Level Factors for Natural Gas Production
- §7.2.2 Table 7-12: Component-Level Average Factors (EPA 1995 / API) by Service (Gas, Light Oil, Heavy Oil, Water/Oil)
- §7.2.2 Table 7-15 & 7-16: Method 21 Screening Ranges (<10,000 ppmv Non-pegged vs >=10,000 ppmv Pegged)
- §7.2.2 Table 7-17 & 7-18: Method 21 Correlation Equations (a * PPM^b & Pegged Defaults)
- §7.2.2 Table 7-19, 7-20 & Subpart W Table W-1E: Optical Gas Imaging (OGI) Leaker Emission Factors
- §7.2.3 Table 7-29: Gathering & Boosting Equipment-Level Average Factors
- §7.2.3 Table 7-30: Gathering & Boosting Component-Level Average Factors

Metadata Schema:
factor_id, API_version, API_section, API_table, source_category, facility_type,
equipment_type, component_type, service_type, pollutant, factor_value, factor_unit,
time_basis, geographic_scope, methodology, source_reference
"""

API_CHAPTER7_ONSHORE_FACTORS = {
    # =========================================================================
    # TIER 1: FACILITY-LEVEL AVERAGE FACTORS (§7.2.2.1, Table 7-8)
    # Audit RC-17 / BUG-110: the Compendium 2021 onshore facility-level factors are per unit of
    # PRODUCTION (Table 7-8), not per facility-day. The former six "well pad / battery" per-day
    # entries (cited as "Table 7-1 / 7-2", which in the 2021 Compendium are not factor tables)
    # were not supported by the source and have been removed.
    # =========================================================================
    "Facility - Onshore Oil Production (Table 7-8)": {
        "factor_id": "API2021_CH7_TAB7_8_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2.1",
        "API_table": "Table 7-8",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Oil",
        "pollutant": "CH4",
        "factor_value": 2.346e-04,
        "factor_unit": "tonne CH4/bbl",
        "time_basis": "throughput",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2.1, Table 7-8",
        "ch4": 2.346e-04,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/bbl",
        "baseline_ch4_mol": 0.788,
        "uncertainty": {"co2": 0.0, "ch4": 0.955, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Onshore oil production facility-level equipment leaks, per barrel of oil produced (0.5173 lb CH4/bbl)",
    },
    "Facility - Onshore Gas Production (Table 7-8)": {
        "factor_id": "API2021_CH7_TAB7_8_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2.1",
        "API_table": "Table 7-8",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Facility",
        "component_type": "Facility",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 2.601e-02,
        "factor_unit": "tonne CH4/10^6 scf",
        "time_basis": "throughput",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Facility Average",
        "source_reference": "API Compendium 2021 Section 7.2.2.1, Table 7-8",
        "ch4": 2.601e-02,
        "co2": 0.0,
        "n2o": 0.0,
        "unit": "tonne CH4/10^6 scf",
        "baseline_ch4_mol": 0.788,
        "uncertainty": {"co2": 0.0, "ch4": 0.529, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_facility",
        "description": "Onshore gas production facility-level equipment leaks, per 10^6 scf of gas produced (57.33 lb CH4/10^6 scf)",
    },

    # =========================================================================
    # TIER 2A: EQUIPMENT-LEVEL FACTORS - ONSHORE OIL PRODUCTION (§7.2.2, Table 7-9)
    # =========================================================================
    "Wellhead - Oil (Heavy Crude)": {
        "factor_id": "API2021_CH7_TAB7_9_WELL_OIL_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Wellhead",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 6.63e-07,
        "factor_unit": "tonne CH4/well/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "WellOilHeavy",
        "type": "equipment",
        "ch4": 6.63e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/well/hr",
        "segment": "Upstream",
        "process_category": "wellhead_fugitive",
        "description": "Oil wellhead fugitive emissions - heavy crude (API < 20°)",
    },
    "Wellhead - Oil (Light Crude)": {
        "factor_id": "API2021_CH7_TAB7_9_WELL_OIL_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Wellhead",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 1.56e-05,
        "factor_unit": "tonne CH4/well/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "WellOilLight",
        "type": "equipment",
        "ch4": 1.56e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/well/hr",
        "segment": "Upstream",
        "process_category": "wellhead_fugitive",
        "description": "Oil wellhead fugitive emissions - light crude (API ≥ 20°)",
    },
    "Separator - Heavy Crude": {
        "factor_id": "API2021_CH7_TAB7_9_SEP_HEAVY",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Separator",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 6.79e-07,
        "factor_unit": "tonne CH4/separator/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "SepHeavy",
        "type": "equipment",
        "ch4": 6.79e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/separator/hr",
        "segment": "Upstream",
        "process_category": "separator_fugitive",
        "description": "Separator fugitive emissions - heavy crude (<20° API)",
    },
    "Separator - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_SEP_LIGHT",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Separator",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 4.10e-05,
        "factor_unit": "tonne CH4/separator/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "SepLight",
        "type": "equipment",
        "ch4": 4.10e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/separator/hr",
        "segment": "Upstream",
        "process_category": "separator_fugitive",
        "description": "Separator fugitive emissions - light crude (≥20° API)",
    },
    # audit RC-17: "Heater-Treater - Heavy Crude" removed — Table 7-9 (Compendium 2021) has no such row
    "Heater-Treater - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEATER_LIGHT",
        # audit RC-17: corrected to the Compendium 2021 Table 7-9 value (was 4.77e-05)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Heater-Treater",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 4.77e-05,
        "factor_unit": "tonne CH4/heater/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaterLight",
        "type": "equipment",
        "ch4": 4.77e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/heater/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Heater-treater fugitive emissions - light crude (≥20° API)",
    },
    "Header - Heavy Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEADER_HEAVY",
        # audit RC-17: corrected to the Compendium 2021 Table 7-9 value (was 4.72e-07)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Header",
        "component_type": "Equipment",
        "service_type": "Heavy Oil",
        "pollutant": "CH4",
        "factor_value": 4.72e-07,
        "factor_unit": "tonne CH4/header/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaderHeavy",
        "type": "equipment",
        "ch4": 4.72e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/header/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Production manifold/header fugitive emissions - heavy crude",
    },
    "Header - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_HEADER_LIGHT",
        # audit RC-17: corrected to the Compendium 2021 Table 7-9 value (was 1.62e-04)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Header",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 1.62e-04,
        "factor_unit": "tonne CH4/header/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "HeaderLight",
        "type": "equipment",
        "ch4": 1.62e-04,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/header/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Production manifold/header fugitive emissions - light crude",
    },
    # audit RC-17: "Storage Tank Fugitive - Heavy Crude" removed — Table 7-9 (Compendium 2021) has no such row
    "Storage Tank Fugitive - Light Crude": {
        "factor_id": "API2021_CH7_TAB7_9_TANK_LIGHT",
        # audit RC-17: corrected to the Compendium 2021 Table 7-9 value (was 2.75e-05)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Storage Tank",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 2.75e-05,
        "factor_unit": "tonne CH4/tank/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "TankFugLight",
        "type": "equipment",
        "ch4": 2.75e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/tank/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Atmospheric crude tank fitting/roof fugitive leaks - light crude",
    },
    "Compressor - Small Reciprocating": {
        "factor_id": "API2021_CH7_TAB7_9_COMP_SMALL_RECIP",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 3.69e-05,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "CompSmall",
        "type": "equipment",
        "ch4": 3.69e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 1.00, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Small reciprocating compressor fugitive emissions (light crude production)",
    },
    "Compressor - Large Reciprocating": {
        "factor_id": "API2021_CH7_TAB7_9_COMP_LARGE_RECIP",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-9",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Crude Oil Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Light Oil",
        "pollutant": "CH4",
        "factor_value": 1.31e-02,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-9",
        "code": "CompLarge",
        "type": "equipment",
        "ch4": 1.31e-02,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 1.00, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Large reciprocating compressor fugitive emissions (light crude production)",
    },

    # =========================================================================
    # TIER 2A: EQUIPMENT-LEVEL FACTORS - ONSHORE GAS PRODUCTION (§7.2.2, Table 7-10)
    # =========================================================================
    "Wellhead - Gas": {
        "factor_id": "API2021_CH7_TAB7_10_WELL_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Wellhead",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.80e-05,
        "factor_unit": "tonne CH4/well/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "WellGas",
        "type": "equipment",
        "ch4": 1.80e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.257, "n2o": 0.0},
        "unit": "tonne CH4/well/hr",
        "segment": "Upstream",
        "process_category": "wellhead_fugitive",
        "description": "Natural gas wellhead fugitive emissions",
    },
    "Separator - Gas Production": {
        "factor_id": "API2021_CH7_TAB7_10_SEP_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Separator",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 4.42e-05,
        "factor_unit": "tonne CH4/separator/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "SepGas",
        "type": "equipment",
        "ch4": 4.42e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.879, "n2o": 0.0},
        "unit": "tonne CH4/separator/hr",
        "segment": "Upstream",
        "process_category": "separator_fugitive",
        "description": "Separator fugitive emissions in natural gas production",
    },
    "Heater - Gas Production": {
        "factor_id": "API2021_CH7_TAB7_10_HEATER_GAS",
        # audit RC-17: corrected to the Compendium 2021 Table 7-10 value (was 2.75e-05)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Heater",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 4.60e-05,
        "factor_unit": "tonne CH4/heater/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "HeaterGas",
        "type": "equipment",
        "ch4": 4.60e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.60, "n2o": 0.0},
        "unit": "tonne CH4/heater/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Inline heater/bath heater fugitive emissions in gas production",
    },
    "Gas Dehydrator Unit - Fugitive Leaks": {
        "factor_id": "API2021_CH7_TAB7_10_DEHY_GAS",
        # audit RC-17: corrected to the Compendium 2021 Table 7-10 value (was 2.31e-05)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Dehydrator",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 7.13e-05,
        "factor_unit": "tonne CH4/unit/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "DehyFugGas",
        "type": "equipment",
        "ch4": 7.13e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.50, "n2o": 0.0},
        "unit": "tonne CH4/unit/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Piping and component fugitive leaks on gas dehydration units",
    },
    "Meter / Piping Run - Gas Production": {
        "factor_id": "API2021_CH7_TAB7_10_METER_RUN_GAS",
        # audit RC-17: corrected to the Compendium 2021 Table 7-10 value (was 1.70e-05)
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Meter Run",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 3.52e-05,
        "factor_unit": "tonne CH4/run/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "MeterRunGas",
        "type": "equipment",
        "ch4": 3.52e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.70, "n2o": 0.0},
        "unit": "tonne CH4/run/hr",
        "segment": "Upstream",
        "process_category": "equipment_fugitive",
        "description": "Sales/allocation meter runs and associated valves/piping in gas production",
    },
    "Compressor - Gas Production Small Recip": {
        "factor_id": "API2021_CH7_TAB7_10_COMP_GAS_SMALL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 2.12e-04,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "CompGasSmall",
        "type": "equipment",
        "ch4": 2.12e-04,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 1.27, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Small reciprocating gas compressor in gas production",
    },
    "Compressor - Gas Production Large Recip": {
        "factor_id": "API2021_CH7_TAB7_10_COMP_GAS_LARGE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-10",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Natural Gas Production",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.22e-02,
        "factor_unit": "tonne CH4/compressor/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-10",
        "code": "CompGasLarge",
        "type": "equipment",
        "ch4": 1.22e-02,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 2.02, "n2o": 0.0},
        "unit": "tonne CH4/compressor/hr",
        "segment": "Upstream",
        "process_category": "compressor_fugitive",
        "description": "Large reciprocating gas compressor in gas production",
    },

    # =========================================================================
    # TIER 2B: COMPONENT-LEVEL AVERAGE FACTORS (§7.2.2, Table 7-12)
    # EPA 1995 Protocol Onshore Production Factors (kg TOC/hr/component)
    # =========================================================================
    "Component - Valve (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.0045,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 2.94e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0045,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in gas/vapor service (EPA 1995 Protocol Table 2-4)",
    },
    "Component - Valve (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.0025,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.63e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0025,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in light oil service (API ≥ 20°)",
    },
    "Component - Valve (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 8.4e-06,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 5.48e-09,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 8.4e-06,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in heavy oil service (API < 20°)",
    },
    "Component - Valve (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_VALVE_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Valve",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 9.8e-05,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 6.39e-08,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 9.8e-05,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Valves in water/oil emulsion service (>50% water)",
    },
    "Component - Pump Seal (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PUMP_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Pumps",
        "component_type": "Pump Seal",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.013,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 8.48e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.013,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.35, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pump seals in light oil service",
    },
    "Component - Pump Seal (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PUMP_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Pumps",
        "component_type": "Pump Seal",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 2.4e-05,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.57e-08,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 2.4e-05,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pump seals in water/oil emulsion service",
    },
    "Component - Connector (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.0002,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.3e-07,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0002,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Threaded / compression connectors in gas service",
    },
    "Component - Connector (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.00021,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.37e-07,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00021,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Connectors in light oil service",
    },
    "Component - Connector (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 7.5e-06,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 4.89e-09,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 7.5e-06,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Connectors in heavy oil service",
    },
    "Component - Connector (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_CONN_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Connector",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.00011,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 7.18e-08,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00011,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Connectors in water/oil service",
    },
    "Component - Flange (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.00039,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 2.54e-07,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00039,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in gas service",
    },
    "Component - Flange (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.00011,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 7.18e-08,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00011,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in light oil service",
    },
    "Component - Flange (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 3.9e-07,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 2.54e-10,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 3.9e-07,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in heavy oil service",
    },
    "Component - Flange (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_FLANGE_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Flange",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 2.9e-06,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.89e-09,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 2.9e-06,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Bolted flanges in water/oil service",
    },
    "Component - Open-Ended Line (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.002,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.3e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.002,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in gas service",
    },
    "Component - Open-Ended Line (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.0014,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 9.13e-07,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0014,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in light oil service",
    },
    "Component - Open-Ended Line (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 0.00014,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 9.13e-08,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00014,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in heavy oil service",
    },
    "Component - Open-Ended Line (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_OEL_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Open-Ended Line",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.00025,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 1.63e-07,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.00025,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in water/oil service",
    },
    "Component - Other / PRV (Gas Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_GAS",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Gas",
        "pollutant": "TOC",
        "factor_value": 0.0088,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 5.74e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0088,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in gas service",
    },
    "Component - Other / PRV (Light Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_LIGHT_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Light Oil",
        "pollutant": "TOC",
        "factor_value": 0.0075,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 4.89e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.0075,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.30, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in light oil service",
    },
    "Component - Other / PRV (Heavy Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_HEAVY_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Heavy Oil",
        "pollutant": "TOC",
        "factor_value": 3.2e-05,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 2.09e-08,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 3.2e-05,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in heavy oil service",
    },
    "Component - Other / PRV (Water/Oil Service)": {
        "factor_id": "API2021_CH7_TAB7_11_PRV_WATER_OIL",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.2",
        "API_table": "Table 7-12",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Production",
        "equipment_type": "Piping & Wellhead Components",
        "component_type": "Pressure Relief Valve",
        "service_type": "Water/Oil",
        "pollutant": "TOC",
        "factor_value": 0.014,
        "factor_unit": "kg TOC/hr/component",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.2, Table 7-12 / EPA 1995 Protocol",
        "ch4": 9.13e-06,  # Table 7-12 converted: tonne CH4/hr/component (81.6 mol %)
        "co2": 0.0,
        "n2o": 0.0,
        "toc_ef_kg_hr": 0.014,
        "unit": "tonne CH4/hr/component",
        "uncertainty": {"co2": 0.20, "ch4": 0.40, "n2o": 0.0},
        "segment": "Upstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valves / other components in water/oil service",
    },

    # =========================================================================
    # TIER 2: GATHERING & BOOSTING EQUIPMENT & COMPONENT FACTORS (§7.2.3, Tab 7-29, 7-30)
    # =========================================================================
    "Gathering - Compressor": {
        "factor_id": "API2021_CH7_TAB7_29_GATH_COMP",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-29",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Compressor",
        "component_type": "Equipment",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.84e-03,
        "factor_unit": "tonne CH4/unit/hr",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Equipment Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-29",
        "code": "GathComp",
        "type": "equipment",
        "ch4": 1.84e-03,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.14, "n2o": 0.0},
        "unit": "tonne CH4/unit/hr",
        "segment": "Midstream",
        "process_category": "gathering_boosting",
        "description": "Gathering compressor fugitive emissions",
    },
    "Component - Block Valve (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_BLOCK_VALVE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Block Valve",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 4.36e-06,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "BlockValve",
        "type": "component",
        "ch4": 4.36e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Block valve fugitive emissions in gathering & boosting",
    },
    "Component - Control Valve (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_CONTROL_VALVE",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Control Valve",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.11e-05,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "ControlValve",
        "type": "component",
        "ch4": 1.11e-05,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Control valve fugitive emissions in gathering & boosting",
    },
    "Component - Connector (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_CONN_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Connector",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 9.79e-07,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "ConnNonComp",
        "type": "component",
        "ch4": 9.79e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Connector fugitive emissions in gathering & boosting",
    },
    "Component - Flange (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_FLANGE_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Flange",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.05e-06,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "FlangeGath",
        "type": "component",
        "ch4": 1.05e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Flange fugitive emissions in gathering & boosting",
    },
    "Component - Pressure Relief Valve (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_PRV_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Pressure Relief Valve",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.39e-07,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "PRV",
        "type": "component",
        "ch4": 1.39e-07,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Pressure relief valve fugitive emissions in gathering & boosting",
    },
    "Component - Pressure Regulator (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_REGULATOR_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Pressure Regulator",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.87e-06,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "Regulator",
        "type": "component",
        "ch4": 1.87e-06,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Pressure regulator fugitive emissions in gathering & boosting",
    },
    "Component - Compressor Seal (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_COMP_SEAL_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Compressor Seal",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.54e-04,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "CompSeal",
        "type": "component",
        "ch4": 1.54e-04,
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Compressor seal fugitive emissions in gathering & boosting",
    },
    "Component - Open-Ended Line (Gathering)": {
        "factor_id": "API2021_CH7_TAB7_30_OEL_GATH",
        "API_version": "API Compendium 2021",
        "API_section": "Section 7.2.3",
        "API_table": "Table 7-30",
        "source_category": "Equipment Leaks",
        "facility_type": "Onshore Gathering & Boosting",
        "equipment_type": "Gathering Station",
        "component_type": "Open-Ended Line",
        "service_type": "Gas",
        "pollutant": "CH4",
        "factor_value": 1.20e-05,
        "factor_unit": "tonne CH4/hr/source",
        "time_basis": "hourly",
        "geographic_scope": "US Average / Accepted Global",
        "methodology": "Component Average",
        "source_reference": "API Compendium 2021 Section 7.2.3, Table 7-30",
        "code": "OELGath",
        "type": "component",
        "ch4": 7.09e-05,  # Table 7-30: 2.39E-01 kg THC/h
        "co2": 0.0,
        "n2o": 0.0,
        "uncertainty": {"co2": 0.0, "ch4": 0.30, "n2o": 0.0},
        "unit": "tonne CH4/hr/source",
        "segment": "Midstream",
        "process_category": "fugitive_component",
        "description": "Open-ended lines in gathering & boosting",
    },
}

# =============================================================================
# TIER 3A: METHOD 21 SCREENING RANGES FACTORS (§7.2.2, Table 7-15 & Table 7-16)
# Expressed in kg TOC/hr/component
# Non-pegged (<10,000 ppmv) and Pegged (>=10,000 ppmv)
# =============================================================================
# Table 7-26: EPA onshore oil and natural gas production equipment leak screening factors
# (EPA-453/R-95-017 Table 2-8), kg TOC/component-hr for screening values < 10,000 and >= 10,000 ppmv.
# None = "NA" in the table (no factor): a count in that range is rejected.
def _m21(below, above):
    return {"non_pegged_ef": below, "pegged_10k_ef": above, "unit": "kg TOC/hr/component", "table": "Table 7-26"}


METHOD21_SCREENING_RANGES = {
    "valve_gas": _m21(2.5e-05, 9.8e-02), "valve_light_oil": _m21(1.9e-05, 8.7e-02),
    "valve_water_oil": _m21(9.7e-06, 6.4e-02), "valve_heavy_oil": _m21(8.4e-06, None),
    "pump_seal_gas": _m21(3.5e-04, 7.4e-02), "pump_seal_light_oil": _m21(5.1e-04, 1.0e-01),
    "pump_seal_water_oil": _m21(2.4e-05, None),
    "other_gas": _m21(1.2e-04, 8.9e-02), "other_light_oil": _m21(1.1e-04, 8.3e-02),
    "other_water_oil": _m21(5.9e-05, 6.9e-02), "other_heavy_oil": _m21(3.2e-05, None),
    "connector_gas": _m21(1.0e-05, 2.6e-02), "connector_light_oil": _m21(9.7e-06, 2.6e-02),
    "connector_water_oil": _m21(1.0e-05, 2.8e-02), "connector_heavy_oil": _m21(7.5e-06, None),
    "flange_gas": _m21(5.7e-06, 8.2e-02), "flange_light_oil": _m21(2.4e-06, 7.3e-02),
    "flange_heavy_oil": _m21(3.9e-07, None), "flange_water_oil": _m21(2.9e-06, None),
    "open_ended_line_gas": _m21(1.5e-05, 5.5e-02), "open_ended_line_light_oil": _m21(1.4e-05, 4.4e-02),
    "open_ended_line_heavy_oil": _m21(7.2e-06, 3.0e-02), "open_ended_line_water_oil": _m21(3.5e-06, 3.0e-02),
}
# Table 7-12: EPA average oil and gas production component leak factors (EPA-453/R-95-017
# Table 2-4): kg gas/component-hr, the converted tonne CH4/component-hr at the 81.6 mol % CH4 basis,
# and the whole-gas scf/component-hr. No pump-seal / heavy-oil row.
def _t712(kg_gas, t_ch4, scf):
    return {"kg_gas_hr": kg_gas, "ch4_t_hr": t_ch4, "scf_hr": scf, "ch4_basis": 0.816, "table": "Table 7-12"}


COMPONENT_FACTORS_T7_12 = {
    "valve_gas": _t712(4.5e-03, 2.94e-06, 1.88e-01), "valve_heavy_oil": _t712(8.4e-06, 5.48e-09, 3.51e-04),
    "valve_light_oil": _t712(2.5e-03, 1.63e-06, 1.05e-01), "valve_water_oil": _t712(9.8e-05, 6.39e-08, 4.10e-03),
    "connector_gas": _t712(2.0e-04, 1.30e-07, 8.36e-03), "connector_heavy_oil": _t712(7.5e-06, 4.89e-09, 3.14e-04),
    "connector_light_oil": _t712(2.1e-04, 1.37e-07, 8.78e-03), "connector_water_oil": _t712(1.1e-04, 7.18e-08, 4.60e-03),
    "flange_gas": _t712(3.9e-04, 2.54e-07, 1.63e-02), "flange_heavy_oil": _t712(3.9e-07, 2.54e-10, 1.63e-05),
    "flange_light_oil": _t712(1.1e-04, 7.18e-08, 4.60e-03), "flange_water_oil": _t712(2.9e-06, 1.89e-09, 1.21e-04),
    "open_ended_line_gas": _t712(2.0e-03, 1.30e-06, 8.36e-02), "open_ended_line_heavy_oil": _t712(1.4e-04, 9.13e-08, 5.85e-03),
    "open_ended_line_light_oil": _t712(1.4e-03, 9.13e-07, 5.85e-02), "open_ended_line_water_oil": _t712(2.5e-04, 1.63e-07, 1.05e-02),
    "pump_seal_gas": _t712(2.4e-03, 1.57e-06, 1.00e-01), "pump_seal_light_oil": _t712(1.3e-02, 8.48e-06, 5.44e-01),
    "pump_seal_water_oil": _t712(2.4e-05, 1.57e-08, 1.00e-03),
    "other_gas": _t712(8.8e-03, 5.74e-06, 3.68e-01), "other_heavy_oil": _t712(3.2e-05, 2.09e-08, 1.34e-03),
    "other_light_oil": _t712(7.5e-03, 4.89e-06, 3.14e-01), "other_water_oil": _t712(1.4e-02, 9.13e-06, 5.85e-01),
}

# Table C-1 "generic" CH4 weight fraction of THC for component emissions, by service
METHOD21_CH4_WT_DEFAULT = {"gas": 0.920, "light_oil": 0.613, "heavy_oil": 0.942}

# Table 7-23: default whole-gas leaker factors (scf gas/component-hr) for surveys under
# 40 CFR 98.234(a)(1)-(6) (OGI and Method 21 at 10,000 ppmv); CH4 basis 81.6 mol %.
# Leakers only: the table has no non-leaker factor.
_OGI_GAS = {"valve": 4.9, "flange": 4.1, "connector": 1.3, "open_ended_line": 2.8, "prv": 4.5, "pump_seal": 3.7, "other": 4.5}
_OGI_CRUDE = {"valve": 3.2, "flange": 2.7, "connector": 1.0, "open_ended_line": 1.6, "prv": 3.7, "pump_seal": 3.7, "other": 3.1}
OGI_LEAKER_FACTORS = {
    **{f"{k}_gas": {"whole_gas_scf_hr": v, "ch4_basis": 0.816, "table": "Table 7-23"} for k, v in _OGI_GAS.items()},
    **{f"{k}_light_crude": {"whole_gas_scf_hr": v, "ch4_basis": 0.816, "table": "Table 7-23"} for k, v in _OGI_CRUDE.items()},
    **{f"{k}_heavy_crude": {"whole_gas_scf_hr": v, "ch4_basis": 0.816, "table": "Table 7-23"} for k, v in _OGI_CRUDE.items()},
}

# Default stream compositions by service classification (API Compendium 2021)
DEFAULT_SERVICE_COMPOSITIONS = {
    "Gas": {"ch4_mol": 0.85, "co2_mol": 0.01, "nmhc_mol": 0.14, "mw": 18.5, "ch4_wt_in_toc": 0.85},
    "Light Oil": {"ch4_mol": 0.60, "co2_mol": 0.005, "nmhc_mol": 0.395, "mw": 24.0, "ch4_wt_in_toc": 0.60},
    "Heavy Oil": {"ch4_mol": 0.15, "co2_mol": 0.002, "nmhc_mol": 0.848, "mw": 32.0, "ch4_wt_in_toc": 0.15},
    "Water/Oil": {"ch4_mol": 0.10, "co2_mol": 0.001, "nmhc_mol": 0.899, "mw": 28.0, "ch4_wt_in_toc": 0.10},
}
